### ISSUE TITLE
[nssdca-delivery] SBN/PSI Batch #21

### ISSUE THREAD

**Issue by neese** [NASA-PDS/operations#170]
## Discipline Node Information

**Delivering Node**: _please enter your DN here for record keeping purposes_
PDS_PSI

**NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
https://sbnarchive.psi.edu/pds4/deep_archive_deliveries/sbnpsi_batch_21_20211021.zip

**Validation report**: _please upload a TXT report or screenshot of PDS4 Validate Tool run on your bundle. NSSDCA only accepts valid PDS4 bundles. be sure you run validate with the `-R pds4.bundle` flag enabled to ensure all integrity checks are completed successfully._
https://sbnarchive.psi.edu/pds4/val_reports/val_reports_batch21.zip

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@neese, these 5 AIP/SIP sets from batch 21 have been archived.
