### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:irtf_io_photometry

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#175]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[irtf_io_photometry_20211110.tar.gz](https://github.com/NASA-PDS/operations/files/7515957/irtf_io_photometry_20211110.tar.gz)

**Validation report**: 
[irtf_io_photometry.txt](https://github.com/NASA-PDS/operations/files/7515961/irtf_io_photometry.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth, hello! I see that you've submitted a number of these requests in the past few days. If this would be helpful, you can also submit multiple AIP/SIP sets for delivery in one ticket, such as done in this ticket: https://github.com/NASA-PDS/operations/issues/170. Let me know if you have any questions about this, and in the meantime, I will get started on your items.

**Comment by tinagueth** [comment]
Hi

Thanks for letting me know. Sorry for all the individual submissions. I will take for larger future submissions.

Thank you,
 Tina
________________________________

**Comment by c-suh** [comment]
No apology necessary! I appreciate your dedication to supplying the information in each ticket.

**Comment by c-suh** [comment]
@tinagueth, this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:irtf_io_photometry_v1.0_20211110

**Comment by smclaughlin7** [comment]
@c-suh Hi, Catherine:  Do you recommend that Tina @tinagueth zip the Deep Archive packages and validation reports, then submit as one issue, like SBN-PSI node has done in the past, e.g. https://github.com/NASA-PDS/operations/issues/114?  Just curious. Thanks!

**Comment by c-suh** [comment]
@smclaughlin7 and @tinagueth - actually, yes! Thank you for catching the (absence of) wording from my [comment above](https://github.com/NASA-PDS/operations/issues/175#issuecomment-967730062). Not only could it be helpful for the submitter, it would be helpful for us at Operations (and NSSDCA) for multiple packages and reports to be submitted in fewer issues/tickets.

For future submissions, if there are more than a handful of packages (e.g. 3 packages), I do recommend that these be submitted in a single issue with one .zip file for the packages and one .zip file for the reports. If the number is more than a handful (e.g. 50 packages), these can be submitted in batches (e.g. 10) across multiple issues, with one .zip file for the packages and one .zip file for the reports per issue.

@smclaughlin7, is there a sweet spot in the amount of packages delivered for your process? The actual numbers are somewhat arbitrary for me as any reduction in the one-to-one ratio of a package to an issue-ticket will definitely boost the rate at which we can deliver these packages, although having more than 20 in one made it a little troublesome to track (I'm thinking of https://github.com/NASA-PDS/operations/issues/60, which turned into about 40 packages in the one issue).

@tinagueth, I appreciate you allowing me to hijack this open issue to fine-tune the procedural details with Stef. Just to clarify, there is no need for you to re-submit any packages.

Thank you both!

**Comment by tinagueth** [comment]
Hi

Thank you for the clarification on not needing to re-submit my previously submissions, and inclusion so that I can do future uploads differently. This comes also in handy as I have several more files that I am getting ready to upload. For those I will follow the new process as stated.

Thank you,
 Tina

P.S.: what is the reason for including the usernames with @ symbol? And when should that be done? Still new to the submission operation process. Thanks!

________________________________

**Comment by tinagueth** [comment]
Hi

I had one more question in regards to submitting multiple packages/reports at the same time. What do should be put for this part then, as there are different lidvid in this case? If listing all of them, should they be separated by a comma or semi-column?

[nssdca-delivery] <replace this with bundle lidvid>

Thanks,
 Tina
________________________________

**Comment by c-suh** [comment]
Hi @tinagueth
- The use of an @mention is the most sure way to notify a person of a comment that he or she may not otherwise see. Of course, the occasional email will still slip by without being read, but without an @mention or active checking of an open issue, oftentimes that person will not know that a new comment has been posted. So, if a comment is meant for a specific person, opposed to a general status update for yourself, I would use an @mention with that person's GitHub username.
- regarding the title or `<replace this with bundle lidvid>`, something mildly descriptive is fine (e.g. `SBN-PSI Batch #xx` or `GEO Apollo & misc`)

**Comment by smclaughlin7** [comment]
> @smclaughlin7, is there a sweet spot in the amount of packages delivered for your process? The actual numbers are somewhat arbitrary for me as any reduction in the one-to-one ratio of a package to an issue-ticket will definitely boost the rate at which we can deliver these packages, although having more than 20 in one made it a little troublesome to track (I'm thinking of #60, which turned into about 40 packages in the one issue).

@c-suh @tinagueth  There really isn't a sweet spot for our NSSDCA process. If 100 new packages are posted in your online repository, our crawler will grab those new items and automatically pass them to our NSSDCA process.

However I do agree that more than 20 Deep Archive packages per a submission ticket/issue is a tricky to track here, and if there are problems that need to be addressed and fixed.  You're welcome to encourage the nodes to aim for at most 20 packages (or perhaps only 10?) per ticket/issue.  Do you have a preference?

**Comment by c-suh** [comment]
@smclaughlin7, OK; good to know. I've updated the issue template to encourage multiple packages of 3 to 10 to an issue. I figure that if needed, it'll be better to raise the cap, as opposed to trying to rein it in, but I think we'll be fine either way. Appreciate your input!

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `irtf_io_photometry` has been archived.
