### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:wt_threshold_speed

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#176]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[wt_threshold_speed_20211110.tar.gz](https://github.com/NASA-PDS/operations/files/7516007/wt_threshold_speed_20211110.tar.gz)

**Validation report**: 
[wt_threshold_speed.txt](https://github.com/NASA-PDS/operations/files/7516009/wt_threshold_speed.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth, this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:irtf_io_photometry_v1.0_20211110

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `wt_threshold_speed` has been archived.
