### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:coiss_zonal_winds

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#180]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[coiss_zonal_winds_20211110.tar.gz](https://github.com/NASA-PDS/operations/files/7516380/coiss_zonal_winds_20211110.tar.gz)

**Validation report**:
[coiss_zonal_winds.txt](https://github.com/NASA-PDS/operations/files/7516381/coiss_zonal_winds.txt)
 

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:coiss_zonal_winds_v1.0_20211110

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `coiss_zonal_winds` has been archived.
