### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:corsstpp

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#181]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[titan_profiles_20211112.tar.gz](https://github.com/NASA-PDS/operations/files/7529297/titan_profiles_20211112.tar.gz)

**Validation report**: 
[titan_profiles_bundle.txt](https://github.com/NASA-PDS/operations/files/7529301/titan_profiles_bundle.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:corsstpp_v2.0_20211112

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `corsstpp` has been archived.
