### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:lowell_uranus-neptune-photometry

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#182]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[lowell_uranus-neptune_20211112.tar.gz](https://github.com/NASA-PDS/operations/files/7529382/lowell_uranus-neptune_20211112.tar.gz)

**Validation report**:
[lowell_uranus-neptune-photometry.txt](https://github.com/NASA-PDS/operations/files/7529383/lowell_uranus-neptune-photometry.txt)
 

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:lowell_uranus-neptune-photometry_v1.0_20211112

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `lowell_uranus-neptune-photometry` has been archived.
