### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:hot_ion_atmos_escape

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#183]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[hot_ion_atmos_escape_20211112.tar.gz](https://github.com/NASA-PDS/operations/files/7529459/hot_ion_atmos_escape_20211112.tar.gz)

**Validation report**: 
[hot_ion_atmos_escape.txt](https://github.com/NASA-PDS/operations/files/7529460/hot_ion_atmos_escape.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:hot_ion_atmos_escape_v1.0_20211112

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `hot_ion_atmos_escape` has been archived.
