### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:corss_occul_el_dens

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#184]
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[corss_occul_el_dens_20211112.tar.gz](https://github.com/NASA-PDS/operations/files/7529621/corss_occul_el_dens_20211112.tar.gz)

**Validation report**: 
[corss_occul_el_dens.txt](https://github.com/NASA-PDS/operations/files/7529624/corss_occul_el_dens.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:corss_occul_el_dens_v1.0_20211112

**Comment by c-suh** [comment]
@tinagueth the AIP/SIP set for `corss_occul_el_dens` has been archived.
