### ISSUE TITLE
[lid-request] urn:nasa:pds:lro_lola_edr

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/operations#193]
* **PDS4 LID:** urn:nasa:pds:lro_lola_edr

* **LID Type:** Bundle
  
* **Mission:** LRO

* **Responsible Node:** Geosciences

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
@sslavney approved
