### ISSUE TITLE
Deploy B12.0

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#197]
Note: For this build, let's be sure that all changes are on AWS websites and services.

- [x] Update latest software release on nasa-pds.github.io (@tloubrieu-jpl)

- [x] Discipline LDD Release
   - [x] [Stage LDD Release](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-StageLDDRelease) (@c-suh )
   - [x] [Post Release Updates](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PostReleaseUpdates) (@c-suh )
   - [x] Send @jshughes latest dLDDs (procedure TBD per @jordanpadams) (@c-suh)

- [x] Create `pds-gamma-aws` for new Staging Environment (@viviant100)

- [ ] Deployment of Staging EN Registry (`pdscloud-staging`?)
    - [ ] [Document deployment procedure](https://wiki.jpl.nasa.gov/display/PDSEN/AWS+Registry+Deployments) for AWS Registry deployments here (@jimmie)
    - [ ] Deploy AWS Services using Terraform scripts (upgrade of ES) (@jimmie)

- [ ] Deployment of Operational EN Registry (`pdscloud-prod1`?)
    - [ ] Deploy AWS Services using Terraform scripts (upgrade of ES) (@jimmie)

- [ ] Deployment of Demo EN Registry
    - [ ] Deploy AWS Services using Terraform scripts (upgrade of ES) (@jimmie)

- [x] Webpage Updated
   - [x] Final step of Stage Release to update pds-prod machines with staged data [Stage IM Release](https://wiki.jpl.nasa.gov/display/PDSEN/PDS4+IM+Release#PDS4IMRelease-StageRelease) (@c-suh)
   - [x] Re-generate WebHelp (@jshughes)
   - [x] Update website with latest WebHelp (@c-suh)
   - [x] Update TBD other web pages per system release ? (@c-suh)

- [ ] Released to the Public
   - [ ] Send out notification (@jordanpadams)

**Once AWS registry deployments have been completed for EN**

- [ ] Ingest data into Staging EN Registry (`pdscloud-gamma`?)
    - [x] Install tools on staging machine and test (@c-suh)
    - [ ] Ingest EN context, data, etc. (@rchenatjpl)

- [ ] Ingest data into Ops EN Registry (`pdscloud-prod`?)
    - [x] Install tools on ops machine and test (@c-suh)
    - [ ] Ingest EN context, data, etc. (@rchenatjpl)

- [ ] Ingest data into Demo EN Registry (`pdscloud-demo`?)
    - [ ] Install tools on demo machine and test (@c-suh)
    - [ ] Ingest demo data (@c-suh / @tloubrieu-jpl )

**Comment by viviant100** [comment]
pdscloud-gamma has been setup and can be reached directly at 35.166.125.154. It is a 1:1 replica of pdscloud-prod1.   @tloubrieu-jpl @jimmie please checkout pdscloud-gamma and let me know if you see any issues.  Thanks.

**Comment by tloubrieu-jpl** [comment]
- primary copy of webcontent stays on prem and is synchronized with pdscloud-gamma.
- all the other resources (data, tools) are only on AWS (there was a one time synchronization)

**Comment by c-suh** [comment]
status for csuh:
- am hammering out details via email for necessary steps with the introduction of AWS gamma (e.g. backup in lieu of svn)
- deployment of registry-app is currently blocked (related to https://github.com/NASA-PDS/operations/issues/196)
- will get started on tasks for Discipline LDD Release

**Comment by c-suh** [comment]
@jordanpadams, I need (more) clarification for the Discipline LDDs Release process:
1. Are the "other release staging steps" mentioned in the last step of the [Stage LDD Release process](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-StageLDDRelease) just the webpage updates or are there other steps?
2. Does "post release" mean after the release has been made public?
3. On what machine should the Post Release Updates be run on - prod or gamma or both? (Note: I made a few edits for this python file as well)

**Comment by tloubrieu-jpl** [comment]
@viviant100 , should I be able to ssh in pdscloud-gamma, my password does not work ?

**Comment by viviant100** [comment]
@tloubrieu-jpl try this:
% ssh ec2-35-166-125-154.us-west-2.compute.amazonaws.com

**Comment by c-suh** [comment]
Note: questions regarding Discipline LDD have been answered in separate meeting. Those steps should be finished today.

**Comment by c-suh** [comment]
Note: Staging LDD Release is blocked by .htaccess issue. Ticket was been submitted yesterday to SAs.

**Comment by jordanpadams** [comment]
@c-suh can you provide some more details and maybe I can help? Can you check the permissions on the files to make sure they match pds-gamma?

Otherwise, it may be a setting the SAs need to enable on the webs server

**Comment by c-suh** [comment]
@jordanpadams, the permissions were slightly different (664 vs 644), but matching them didn't change it. Here's the SA ticket: https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1027

**Comment by jordanpadams** [comment]
@c-suh copy that. Thanks!

**Comment by c-suh** [comment]
**Webpage updated:** have most changes local and ready to be committed, pushed, then tested on gamma.

**Comment by c-suh** [comment]
@jordanpadams and @viviant100 , this is out of order with the action items in https://github.com/NASA-PDS/operations/issues/198, but all Webpage updates for b12.0 are operational (https://pds.nasa.gov/datastandards/about/).

**Comment by c-suh** [comment]
**Note for registry-app:** the [tar.gz](https://github.com/NASA-PDS/pds-registry-app/releases/download/v1.0.2/pds-registry-app-1.0.2-bin.tar.gz) does not have a `supplementer-1.0.0/` or `test/` directory as expected from https://nasa-pds.github.io/pds-registry-app/install/tools.html#. 

This has been installed on AWS gamma and AWS prod1. Added symlinks and adjusted accordingly when updating the PATH environment variables.

**Comment by tloubrieu-jpl** [comment]
@c-suh this is a bug, the supplementer should be in there but I missed to update the configuration which builds the package.

**Comment by jordanpadams** [comment]
closing as other tickets are open for each of these remaining tasks
