### ISSUE TITLE
[ldd-release] Legacy LDD JSONs

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#201]
We need to simply add these JSON files to the online archives alongside their existing XSD/SCH. No need to add them to ZIP files. This is really for our internal tool use for the time being. (obviously rename them back to .JSON)

* [PDS4_SP_1100.JSON.txt](https://github.com/NASA-PDS/operations/files/7673869/PDS4_SP_1100.JSON.txt)
* [PDS4_PARTICLE_1100.JSON.txt](https://github.com/NASA-PDS/operations/files/7673873/PDS4_PARTICLE_1100.JSON.txt)
* [PDS4_ALT_1H00_1000.JSON.txt](https://github.com/NASA-PDS/operations/files/7673874/PDS4_ALT_1H00_1000.JSON.txt)

**Comment by c-suh** [comment]
@jordanpadams question about the filenames: should match the existing LDD files for that IM and LDD version? e.g.
PDS4_ALT_1000.JSON
PDS4_PARTICLE_1H00_1100.JSON
PDS4_SP_1100.JSON _(same)_

**Comment by jordanpadams** [comment]
Yes.

For Particle though, it is intend for this one: http://pds.nasa.gov/pds4/particle/v1/PDS4_PARTICLE_1100.xsd

Sorry I didn't fix those. I thought I did.

**Comment by jordanpadams** [comment]
@c-suh ☝️

**Comment by c-suh** [comment]
@jordanpadams, sorry, to clarify: does it matter if the IM version inside these JSONs match what's indicated in the .xsd? Or just name all the JSONs with the LDD version only?
Using the original filenames as posted up top:

[PDS4_PARTICLE_1100.JSON.txt](https://github.com/NASA-PDS/operations/files/7673873/PDS4_PARTICLE_1100.JSON.txt):
```
      "IM Version": "1.17.0.0" ,
      "LDD Version": "1.1.0.0" ,
```
[PDS4_PARTICLE_1100.xsd](https://pds.nasa.gov/pds4/particle/v1/PDS4_PARTICLE_1100.xsd):
```
<!--  Generated from the PDS4 Information Model Version 1.4.0.1 - System Build 5b  -->
<xs:import ... schemaLocation="http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1400.xsd"/>
```

---

[PDS4_ALT_1H00_1000.JSON.txt](https://github.com/NASA-PDS/operations/files/7673874/PDS4_ALT_1H00_1000.JSON.txt):
```
      "IM Version": "1.1.0.0" ,
      "LDD Version": "1.0.0.0" ,
```
[PDS4_ALT_1000.xsd](https://pds.nasa.gov/pds4/alt/v1/PDS4_ALT_1000.xsd) _(there is no_ PDS4_ALT_1H00_1000.xsd_)_
```
<!--  Generated from the PDS4 Information Model Version 1.4.0.1 - System Build 5b  -->
<xs:import ... schemaLocation="http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1400.xsd"/>
```

**Comment by jordanpadams** [comment]
@c-suh thanks for digging into the details! Feel free to update as you see fit, but it doesn't matter. this is more for operational use than anything. if we wanted it to be valid, we would also need to update the associated labels and ZIP, which we are not going to do.

**Comment by c-suh** [comment]
JSONs are on prod2 (not prod1) and pushed to the portal-legacy repo. TODO: verify retiring/deletion of the [pds-data-dictionaries/dd-library repo](https://github.com/pds-data-dictionaries/dd-library) since it and the associated .htaccess file have been folded into the private repo.
