### ISSUE TITLE
[nssdca-delivery] maven.spice, orex.spice, insight.spice, mars2020.spice, ladee.spice, em16_spice

### ISSUE THREAD

**Issue by mcostasitja** [NASA-PDS/operations#202]
## Overview

This delivery consists of a total of 40 SPICE Bundle products
for MAVEN, OSIRIS ReX, Mars2020, LADEE, Insight and ExoMars2016.

Given the number of outputs it has been agreed with Jordan H.
Padams via personal communication, that the deliveries could
be merged in a single issue.

## Discipline Node Information

**Delivering Node**: NAIF

**NSSDCA Delivery Package**:
https://naif.jpl.nasa.gov/pub/naif/misc/mcosta/nssdca/202112/
----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@mcostasitja, these 15 sets have been posted for NSSDCA processing. Starting tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v3.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v10.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v7.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v8.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v9.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:ladee.spice_v1.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v1.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v2.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v24.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v25.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v26.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v27.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v10.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v11.0_20211209
urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v12.0_20211209

**Comment by c-suh** [comment]
@mcostasitja , all SIPs have been archived.
