### ISSUE TITLE
[ldd-release] OREX LDD Version:1.0.0.0 IM Version:1.7.0.0

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/operations#204]
* **Is the LDD IngestLDD in Github?** No
* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 12/17/2021
* **Need-by date rationale**: This is a bugfix for missing files that are affecting existing data.

### Latest LDD is NOT in Github
* **LDD**: OREX
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

Note: We found during OREX testing that version 1.0.0.0 of the OREX mission dictionary was missing from the dictionaries page at (https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml). This submission is intended to correct that issue. These files are the original dictionaries that were originally archived with the mission bundle, except the LID was updated to match the LID edits made in #42.
 
[orex_ldd_OREX_1000.zip](https://github.com/NASA-PDS/operations/files/7694889/orex_ldd_OREX_1000.zip)

**Comment by jstone-psi** [comment]
Sorry, I had a dash instead of an underscore the corrected LID. It should be fixed now.

**Comment by c-suh** [comment]
forgot to validate

**Comment by c-suh** [comment]
@jstone-psi , the LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#orex.
