### ISSUE TITLE
monthly metrics: troubleshoot missing IMG reports 

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#207]
reported by Colleen. Am checking logs first because we've had issues with getting these whenever a node changes anything, e.g. server config, log filename. Initial findings:
- we have November logs for 3 of their machines
- we don't have November logs for a couple
- we don't have logs after May for 3 more
- we don't have logs after Aug 2018 for 1 machine (except one random month for 2019 July)

So

- [ ] is it connections or logs for the missing files?
- [ ] what happened with the logs we do have? Why didn't those generate reports?

**Comment by c-suh** [comment]
Had missed an update from John Blalock back in June explaining 4 sets of the missing logs. The other 2 slipped through the cracks for this past month and have been posted. Must wait for sawmill to finish processing and updating its database (think the issue lies in this step) before pulling the logs.

**Comment by c-suh** [comment]
Process to update the database is being killed in the middle of repeated warnings that multiple database fields have "a very large number of unique values".  Have identified which database fields those are and will attempt to simplify them by adjusting the suppress levels and/or the log filters (specific adjustments TBD). @jordanpadams let me know if you'd like me to confirm the changes with you before I apply them and build the database. 

Note: In the meantime, in preparation for December metrics, I'm pulling logs and pre-processing them from the "back-end".

**Comment by jordanpadams** [comment]
@c-suh i think we have always had those warnings? it shouldn't prevent the build of the metrics, but if so, then we can look into it. I would hate to break something we actually use.

**Comment by c-suh** [comment]
@jordanpadams correct, we do have those warnings for some of the nodes (GEO's is rife with them), but it hadn't been stopping before (that I'd noticed). Switching to email for details.

**Comment by c-suh** [comment]
Have adjusted a few factor , but Jordan pointed out that it's still requiring more RAM than might be available. Sent a request to the SAs to monitor this. https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1176

**Comment by c-suh** [comment]
SAs have increased the memory which allowed for the missing months to be processed. Had to then rebuild the corrupted database, but the missing months have been generated. I will notify IMG, fill in the missing information, then ready the metrics for the new year. After this next month's metrics are done for all nodes, must go back and update the database with information for the months/years prior to the problem months.
