### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:eldorado_nv_dd_ptv

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#210]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[eldorado_20211222.tar.gz](https://github.com/NASA-PDS/operations/files/7764505/eldorado_20211222.tar.gz)

* **Validation report**: 
[eldorado.txt](https://github.com/NASA-PDS/operations/files/7764509/eldorado.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth , this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:eldorado_nv_dd_ptv_v1.0_20211222

**Comment by c-suh** [comment]
@tinagueth the SIP for `eldorado` has been archived.
