### ISSUE TITLE
[ldd-release] ldd-speclib  LDD Version: 1100 IM Version: 1E00, 1F00, 1G00, 1H00

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/operations#222]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes
* **Need-by date**:  June 30, 2022
* **Need-by date rationale**: No hurry

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-speclib/tree/main/build
* **PDS4 IM version to release with**: 1E00, 1F00, 1G00, 1H00

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

**Comment by c-suh** [comment]
@sslavney the LDD for **1E00 1100** has been posted to https://pds.nasa.gov/datastandards/dictionaries/index-pre-1.15.0.0.shtml#speclib.

A note that the other three LDDs (**1F00-1H00 1100**) were already posted at the following pages:
- https://pds.nasa.gov/datastandards/dictionaries/index-1.15.0.0.shtml#speclib
- https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#speclib
- https://pds.nasa.gov/datastandards/dictionaries/index-1.17.0.0.shtml#speclib
