### ISSUE TITLE
[lid-request] viper_nirvss_aim

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/operations#226]
* **PDS4 LID:** viper_nirvss_aim

* **LID Type:** Bundle
  
* **Mission:** VIPER

* **Responsible Node:** Geosciences

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Done 9/11
