### ISSUE TITLE
[lid-request] viper_nirvss_spc

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/operations#228]
* **PDS4 LID:** viper_nirvss_spc

* **LID Type:** Bundle
  
* **Mission:** VIPER

* **Responsible Node:** Geosciences

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Done 7/11
