### ISSUE TITLE
[nssdca-delivery] SBN-PSI Batch #22

### ISSUE THREAD

**Issue by neese** [NASA-PDS/operations#237]
### Discipline Node Information

* **Delivering Node**: _please enter your DN here for record keeping purposes_
* PDS_PSI

* **NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
* https://sbnarchive.psi.edu/pds4/deep_archive_deliveries/sbnpsi_batch_22_20220301.zip

* **Validation report**: _please upload a TXT report or screenshot of PDS4 Validate Tool run on your bundle. NSSDCA only accepts valid PDS4 bundles. be sure you run validate with the `-R pds4.bundle` flag enabled to ensure all integrity checks are completed successfully._
* https://sbnarchive.psi.edu/pds4/val_reports/val_reports_batch22.zip

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@neese, these 5 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:ast-bennu.radar.shape-model_v1.1_20220301
urn:nasa:pds:system_bundle:product_sip_deep_archive:ast-sat.thomas.shape-models_v1.0_20220301
urn:nasa:pds:system_bundle:product_sip_deep_archive:gaskell.ast-eros.shape-model_v1.1_20220301
urn:nasa:pds:system_bundle:product_sip_deep_archive:gaskell.ast-itokawa.shape-model_v1.1_20220301
urn:nasa:pds:system_bundle:product_sip_deep_archive:saturn_satellite_shape_models_v1.0_20220301

**Comment by c-suh** [comment]
@neese, all 5 AIP/SIP sets from batch #22 have been archived.
