### ISSUE TITLE
[ldd-request] Create new LDD "nh"

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/operations#240]
* **Local Data Dictionary Name:**
New Horizons Primary and Extended Missions Namespace

* **Namespace ID Requested:**
nh

* **Discipline or Mission LDD?** 
Mission 

* **Steward Organization Name:** 
SBN

* **LDD Steward Name:** 
Adeline Gicquel (primary), Anne Raugh and Ben Hirsch (secondary)

* **LDD Steward Email:** 
agicquel@umd.edu, araugh@umd.edu, bhirsch1@umd.edu

* **LDD Stewardship Team Members:** 
acraugh (others are not on team list)

* **LDD Description:**
Attributes used for mission-specific metadata in the New Horizons primary mission and extended missions to Kuiper Belt Objects.

* **Rationale for creation of new LDD:**
Migration of primary and first extended mission data to PDS3 underway; subsequent extended missions are required to deliver in PDS4.

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
Hello @acraugh. Just confirming the following two points 
- the lead steward is Adeline Gicquel and will be the point of contact listed on the PDS Namespace Registry list
- you will be the lone member of the NH LDD Stewardship Team and assigned any issues submitted for the NH LDD repository

**Comment by acraugh** [comment]
That's right, @c-suh. Eventually Adeline will either need to dig into github or hand it off to someone who's already familiar. Not clear which will happen, so I'll be the contact until we can do that training/assignment. The team will expand in (I hope) the relatively near future...

**Comment by acraugh** [comment]
Hey @c-suh - What is the holdup with creating the New Horizons mission repo? Is there something I need to do to move this along? Thanks!

**Comment by c-suh** [comment]
Hi @acraugh; sorry about the delay. I'll get on this today, and you should be receiving at least one relevant notification or invitation about a new team or repository.

**Comment by acraugh** [comment]
Thanks @c-suh ! It's not a major deal at this point - the campus is on Spring Break and I'm about to leave town for a week. I just had it on my follow-up list this week and figured better to rattle cages and run away then not rattle them at all. Probably. 😊

**Comment by c-suh** [comment]
@acraugh it was an effective rattle :) enjoy your spring break!

---

Your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-nh. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
