### ISSUE TITLE
[lid-request] vex_virtis_emissivity

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/operations#241]
* **PDS4 LID:** vex_virtis_emissivity

* **LID Type:** Bundle
  
* **Mission:** Venus Express

* **Responsible Node:** Geosciences

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Done. thanks, Susie
