### ISSUE TITLE
monthly metrics: migrate resources to AWS or appropriate machines

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#247]
## 💡 Description
- [x] prem-gamma to pds-rpt: additional Validate and Transform download numbers from Operations script
- [x] starlite to pds-rpt(?): [EN Usage Metrics](https://wiki.jpl.nasa.gov/display/PDSEN/EN+Monthly+PowerPoint#ENMonthlyPowerPoint-Task:ENUsagemetrics)
   - documentation is old. Need to clarify with Colleen what her exact procedure is now
- [x] pds-fs to pds-fs(?): PDS access logs
   - same machine, new directories for new AWS production machines

verify last 2 with @jordanpadams at next meeting

**Comment by jordanpadams** [comment]
@c-suh is the question where to pull the access logs from? I think that would be a question for @jimmie about how/where we can get access logs from AWS. We no longer use an Apache HTTP server (how we got logs before), so we are going to have to figure out how to translate those.

**Comment by c-suh** [comment]
@jordanpadams the question came up because Andrew Zimdars asked about the existing script which pulls the access logs and saves them to a shared directory. I just asked about the apache/aws logs, and he said that the pdscloud instances are running apache, but since the setup is slightly different with AWS, the logs are no longer contained to one system, and he was checking in about how to handle this. He can put the logs from each system into separate directories, or he can append (not merge) prod2's logs to prod1's. The first option seems cleaner to me, but I want to make sure I'm not overlooking anything:
- there's no issue with splitting the logs into separate directories (from `en-http-pds-proxy` to `en-http-pdscloud-prod{1|2}`)
- the involved machines, fs and proxy, are current/good (given that starlite is not)
- the configuration/procedure changes are limited to
   - the commands in step 1 of [gathering monthly tool metrics](https://wiki.jpl.nasa.gov/display/PDSEN/EN+Monthly+PowerPoint#ENMonthlyPowerPoint-Task:ToolMetrics)
   - the Log Source for PDS EN in Sawmill

**Comment by c-suh** [comment]
waiting to hear from SA about new directories. Attempting setup of operations repo on pds-rpt

**Comment by c-suh** [comment]
First item is done (move running of pdsen script to metrics machine). Will send Colleen slightly modified commands.

Third item (EN access logs from AWS to 2 directories):
- 2 directories are set up but the contents are incomplete (there's a partial log for one day). Have opened a ticket [here](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1848).
- In said ticket, also requested the logs be formatted to Apache's Combined Log FOrmat, as mentioned in the [report service documentation](https://wiki.jpl.nasa.gov/display/PDSEN/Report+Service#ReportService-POCs,UsualLogDeliverySchedule,Issues,andResponses)

**Comment by c-suh** [comment]
[Documentation](https://wiki.jpl.nasa.gov/display/PDSEN/EN+Monthly+PowerPoint) has been updated and emails exchanged with Colleen. Missing logs have been supplied and SA says the combined log format is in place, but the April numbers for EN are inexplicably low. Have verified that all April logs were used, but verify the format and if preprocessing is required.

**Comment by c-suh** [comment]
For whatever the reason, most of the logs for April, from both the prem machine and AWS machines, are filled with messages like these:
```
(internal dummy connection)
ELB-HealthChecker/2.0
Amazon-Route53-Health-Check-Service
```
We started getting proper access logs starting from the 26th. Will let Vivian know and ask for next steps, i.e. ask SAs if they can recover information or write this month off as a loss.

**Comment by c-suh** [comment]
Updated page to note that April EN metrics are incomplete. Will monitor metrics for next month but am hopeful that all will be as expected.
