### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mars2020_meda (resubmitted)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#251]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[mars2020_meda.tar.gz](https://github.com/NASA-PDS/operations/files/8605122/mars2020_meda.tar.gz)

* **Validation report**: 
[meda_bundlev3.txt](https://github.com/NASA-PDS/operations/files/8605129/meda_bundlev3.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh I just realized you (re)submitted the Mars 2020 MEDA bundle 10 days ago as part of _**[nssdca-delivery] PDS_ATM Pack#3** #248_ .  If that submission addressed the issues with _**[nssdca-delivery] urn:nasa:pds:mars2020_meda** #154_, and if the MEDA bundle has not changed over the past 10 days, I believe this delivery can be withdrawn/cancelled.  What do you think?

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh  Ah, the Mars2020 MEDA files in both Deep Archive packages #248 and #251 are identical. Also the MEDA bundle (re)submitted via #248 is already in our queue to ingest and archive.  I propose this issue #251 be closed.  Does this make sense to you?

**Comment by tinagueth** [comment]
@smclaughlin7 @c-suh for the #248 submission, the validation report was not correct, hence it was resubmitted. The submission from #154 was an older version of the data volume, I believe version 1, which was not done by me but by Joni.
I am not sure why the version number in the file names has not been updated in this most recent submission as this is version 3 of the data volume, like Mars2020 moxie bundle. I will have to check with Lyle about the file naming in regard to the version number.

**Comment by smclaughlin7** [comment]
@tinagueth Both #248 and #251 submissions are for MEDA bundle v1.0 with LIDVID

> urn:nasa:pds:mars2020_meda::1.0

and the LIDVID for both SIP products (mars2020_meda_v1.0_20220421_sip_v1.0.xml/tab) are identical

> urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020_meda_v1.0_2022042

so checking with Lyle about the version of the bundle / data volume is a good plan, and @c-suh should hold off on posting this delivery #251.  Thanks!

**Comment by tinagueth** [comment]
@smclaughlin7 yes those two should be identical as @c-suh required me to resubmit the MEDA bundle due to the issue with the validation report. However, I just noticed that her comments for that appear in delivery #154 rather than delivery #248

**Comment by c-suh** [comment]
@smclaughlin7 I updated the description for #248 with this validation report, but the package from #248 did not have an issue, so I'd say this is redundant. I had requested this in/for #154, not realizing that @tinagueth had already resubmitted it as part of #248. I will close this issue. Apologies for the confusion!

**Comment by smclaughlin7** [comment]
@c-suh Thanks! I also missed that #248 was a resubmission of #154. Glad you could update the description for #248 with the new validation report from redundant delivery #251 and close #251. Thanks all! @tinagueth

**Comment by smclaughlin7** [comment]
@tinagueth Sure; glad that helped!
