### ISSUE TITLE
[ldd-request] Create new LDD "vgr"

### ISSUE THREAD

**Issue by matthewtiscareno** [NASA-PDS/operations#253]
* **Local Data Dictionary Name:**  Voyager Mission Dictionary

* **Namespace ID Requested:**  vgr

* **Discipline or Mission LDD?**  Mission

* **Steward Organization Name:**  PDS RMS Node

* **LDD Steward Name:**  Matthew Tiscareno

* **LDD Steward Email:**  matt@seti.org

* **LDD Stewardship Team Members:**  Mitch Gordon, Mia Mace

* **LDD Description:**  This dictionary supports data from the Voyager missions

* **Rationale for creation of new LDD:**  This LDD is needed in order to support data providers preparing to deliver Voyager data.

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
Hello @matthewtiscareno - we do have both [Voyager 1](https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#vg1) and [Voyager 2](https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#vg2) LDDs (their repos: [vg1](https://github.com/pds-data-dictionaries/ldd-vg1) and [vg2](https://github.com/pds-data-dictionaries/ldd-vg2). I notice that neither of these are listed in the [PDS Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/blob/main/docs/namespace-registry/pds-namespace-registry.pdf), for which I apologize and am taking steps to remedy).

Would your dictionary differ from either of these?

**Comment by matthewtiscareno** [comment]
Hi.  Yes, we at RMS have discussed this on a thread including Joe Mafi at PPI (steward of the vg1 and vg2 LDDs), as well as representatives from IMG and ATM and the current Voyager data providers.  We all agree that the vg1 and vg2 LDDs should be deprecated and that their content should be subsumed into a unified vgr LDD.  We at RMS have also volunteered to take over the stewardship, and Joe at PPI is good with that.

**Comment by jordanpadams** [comment]
:+1:

**Comment by jordanpadams** [comment]
@c-suh :point-up:

**Comment by c-suh** [comment]
@matthewtiscareno apologies for missing this! In the future, please use "@c-suh" in any comments that I should see so that I'll be notified. Please also provide the GitHub usernames for all members of the LDD Stewardship Team, namely for Mitch Gordon and Mia Mace as I have yours already. Thank you!

**Comment by matthewtiscareno** [comment]
@c-suh:  Apologies for not tagging you.  I didn't realize that you wouldn't be automatically notified of a reply to your own post, and the interface does not seem to have a way to automatically tag when you reply to a post. 

Anyway, the other members of the Stewardship Team are https://github.com/mit3ch and https://github.com/mace-space
I do not know why they are not appearing as people I can tag in this post.  Does this give you enough to go forward?

**Comment by c-suh** [comment]
@matthewtiscareno no worries! If I recall correctly, I changed my notification settings as the default settings were notifying me of too many things within NASA-PDS to be helpful. In general, mentioning me can't hurt, as it should (better) guarantee that I see the comment.

Yes, those links are more than enough; thank you. I'll be in touch again soon!

**Comment by c-suh** [comment]
@matthewtiscareno, @mit3ch, and @mace-space, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-vgr. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started!

**Comment by matthewtiscareno** [comment]
@c-suh:  The repo was created a week ago, and I've already been at work updating the IngestLDD file.  I'm not sure what action was taken today, and I hope it's not any problem that I've already gotten started.  Thanks!

**Comment by c-suh** [comment]
@matthewtiscareno I went a little out of order with the procedure and had created the repo before VGR was officially added to the namespace registry. Fortunately in this case, I don't anticipate any problems!
