### ISSUE TITLE
Upload data to online machines

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#258]
## 💡 Description

I would like to upload `pds-prod1:/data/pds4/test-data/custom-datasets` to pdscloud-prod1/2 and pdscloud-gamma. This is the data to satisy https://github.com/NASA-PDS/pds-api/issues/97

**Comment by jordanpadams** [comment]
@tloubrieu-jpl FYI

**Comment by c-suh** [comment]
The data has been uploaded to pdscloud-prod1/2 and pdscloud-gamma:
https://pds.nasa.gov/data/pds4/test-data/custom-datasets/

(I've left it as is on pds-prod1.)
