### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mess-epps-eps-raw::1.0 and urn:nasa:pds:mess-epps-fips-calibrated::1.0

### ISSUE THREAD

**Issue by bharris-igpp** [NASA-PDS/operations#260]
### Discipline Node Information

* **Delivering Node**: _please enter your DN here for record keeping purposes_
PDS_PPI
* **NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
[PPI_2022-06-01.zip](https://github.com/NASA-PDS/operations/files/8774359/PPI_2022-06-01.zip)

* **Validation report**: _please upload a TXT report or screenshot of PDS4 Validate Tool run on your bundle. NSSDCA only accepts valid PDS4 bundles. be sure you run validate with the `-R pds4.bundle` flag enabled to ensure all integrity checks are completed successfully._
[PPI_2022-06-01_val-reports.zip](https://github.com/NASA-PDS/operations/files/8774398/PPI_2022-06-01_val-reports.zip)

errors listed are known and classified as 'not really errors'

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
Hello @bharris-igpp. Thank you for your submission! In looking over the validation reports you attached in this issue's description, I noticed that each has a single referential integrity error for `error.integrity.missing_version`. For example:
```
  FAIL: file:/pds/archive1/DATA/mess-epps-eps-raw/document/collection-document.xml
      ERROR  [error.integrity.missing_version]   The primary member 'urn:nasa:pds:mess-epps-eps-raw:document:dataset' should include the version number
```
Each report also has a number of referential integrity warnings for `unreferenced_member`s, if you would like to take the opportunity to address these well!

Once done, please attach the corrected and revalidated set in this issue and comment with @c-suh so that I'm notified. Much appreciated!

**Comment by bharris-igpp** [comment]
@c-suh, bundles fixed and new inventories attached:
[mess-epps-eps-raw_inventory_PPI_2022-06-01_v2.zip](https://github.com/NASA-PDS/operations/files/8881882/mess-epps-eps-raw_inventory_PPI_2022-06-01_v2.zip)
[mess-epps-fips-cal_inventory_PPI_2022-06-01_v2.zip](https://github.com/NASA-PDS/operations/files/8881884/mess-epps-fips-cal_inventory_PPI_2022-06-01_v2.zip)

**Comment by c-suh** [comment]
@bharris-igpp thank you very much! Apologies for not specifying this above, but please also attach your validation reports for each resubmitted set. Thank you in advance!

**Comment by bharris-igpp** [comment]
@c-suh, validation reports attached.
[mess-epps-fips-cal_VAL_2022-06-22.txt](https://github.com/NASA-PDS/operations/files/8971141/mess-epps-fips-cal_VAL_2022-06-22.txt)
[mess-epps-eps-raw_VAL_2022-06-21.txt](https://github.com/NASA-PDS/operations/files/8971142/mess-epps-eps-raw_VAL_2022-06-21.txt)

**Comment by c-suh** [comment]
@bharris-igpp thank you very much for both the reports and for upgrading the Validate tool! These 2 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:mess-epps-eps-raw_v1.0_20220609
urn:nasa:pds:system_bundle:product_sip_deep_archive:mess-epps-fips-calibrated_v1.0_20220610

**Comment by c-suh** [comment]
@bharris-igpp the packages for `mess-epps-eps-raw_v1.0_20220609` and `mess-epps-fips-calibrated_v1.0_20220610` have been archived!
