### ISSUE TITLE
[ldd-request] Create new LDD "near"

### ISSUE THREAD

**Issue by klopez1313** [NASA-PDS/operations#261]
* **Local Data Dictionary Name:**
Near Earth Asteroid Rendezvous Mission Dictionary

* **Namespace ID Requested:**
near

* **Discipline or Mission LDD?** 
Mission

* **Steward Organization Name:** 
PDS SBN Node

* **LDD Steward Name:** 
Kristina Lopez

* **LDD Steward Email:** 
klopez@psi,edu

* **LDD Stewardship Team Members:** 
neese

* **LDD Description:**
The mission dictionary for NEAR to support the PDS3 to 4 migration.

* **Rationale for creation of new LDD:**
Needs to support PDS3 mission specific metadata for the near migration

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
@klopez1313, I got the request and will get this going. If leaving any comments for me, please use "@c-suh" in your message, as it greatly increases the chances of my seeing it in a timely manner. Thank you!

**Comment by c-suh** [comment]
Namespace request submitted at https://github.com/NASA-PDS/pds4-information-model/issues/484.

**Comment by c-suh** [comment]
@klopez1313 and @neese, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-near. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started!
