### ISSUE TITLE
[ldd-request] Create new mission LDD "ody"

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#262]
* **Local Data Dictionary Name:**
2001 Mars Odyssey

* **Namespace ID Requested:**
ody

* **Discipline or Mission LDD?** 
mission

* **Steward Organization Name:** 
PDS Geo Node

* **LDD Steward Name:** 
Daniel Politte

* **LDD Steward Email:** 
politte@wunder.wustl.edu

* **LDD Stewardship Team Members:** 
Daniel Politte, Ed Guinness, Paul Geissler, Trent Hare

* **LDD Description:**
This LDD is for mission specific needs for the 2001 Mars Odyssey

* **Rationale for creation of new LDD:**
forthcoming PDS4 migrations.

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
Hi @thareUSGS. I have the GitHub usernames for all of the stewardship team except Paul Geissler, so please provide this. (In the future for any similar requests, the usernames, as prompted in the issue description, would be greatly appreciated!) Thank you!

**Comment by c-suh** [comment]
Note for self: dvpolitte and edguinness. Namespace request submitted at https://github.com/NASA-PDS/pds4-information-model/issues/485.

**Comment by c-suh** [comment]
@dvpolitte, @edguinness, and @thareUSGS - your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-ody. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started!

If you would like Paul Geissler to be added to the [Ody LDD Stewardship Team](https://github.com/orgs/pds-data-dictionaries/teams/ody-ldd-stewardship-team), which has convenient Admin access to the new repo, please let me know his GitHub username. Thank you!

**Comment by c-suh** [comment]
The only aspect of this which is not complete is the addition of Paul Geissler to the Ody LDD Stewardship Team. I'd requested his username (comment just above) and trust that they will get in touch again when it's needed.
