### ISSUE TITLE
[ldd-release] GEOM LDD Version: 1.9.6.0 IM Version: 1.16.0.0

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS/operations#267]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes
* **Need-by date**: 2022-06-06
* **Need-by date rationale**: Mars 2020 IDSO needs the update to prepare archives for an upcoming release.

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: [_Link to specific LDD version's build directory here_](https://github.com/pds-data-dictionaries/ldd-geom/tree/main/build/development/0c8e6fbd3b73a34252eaeaf9a91a52728722b00f/1.16.0.0)

* **PDS4 IM version to release with**: 1.16.0.0

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github
* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
@edguinness, hello! The link in the description takes me to a '404 Page not found', but looking at the URL and at this issue title, I am going to assume this request is for the PDS4_GEOM_1G00_**1960** files in the [build/development/*/](https://github.com/pds-data-dictionaries/ldd-geom/tree/main/build/development/c28ad462dd3698040b86096ff7e9a4d579afbe6c/1.16.0.0) directory and not for the [latest 1G00 release](https://github.com/pds-data-dictionaries/ldd-geom/releases/tag/1G00_1930), which is LDD version 1.9.3.0. Please let me know if this is incorrect! Thank you.

**Comment by jordanpadams** [comment]
@c-suh i just tagged this for @edguinness . He is looking to release this: https://github.com/pds-data-dictionaries/ldd-geom/releases/tag/1G00_1960

**Comment by jordanpadams** [comment]
@c-suh as a note, in the future, if folks reference the `build/development` directory, we should direct them to https://pds-data-dictionaries.github.io/development/ldd-release.html#preparing-a-release for tagging a new release

**Comment by edguinness** [comment]
We want to release geom version 1.9.6.0 built against IM version 1.16.0.0 (1.G.0.0) at the request of the Mars 2020 team. This is my first time trying to request such a release.

**Comment by c-suh** [comment]
@edguinness understood! I appreciate the heads up and empathize as I am constantly learning with this job.

Jordan has tagged the [GEOM 1G00_1960 release](https://github.com/pds-data-dictionaries/ldd-geom/releases/tag/1G00_1960) this time and likely been in touch, but just in case not, here is a link to our documentation on preparing a release: https://pds-data-dictionaries.github.io/development/ldd-release.html#preparing-a-release.

Assuming that this passes the Validate tool, I should have it posted today. Either way, I will let you know. Thank you!

**Comment by edguinness** [comment]
Thanks. Jordan explained what I need wrong.

**Comment by c-suh** [comment]
@edguinness apologies for the delay! This has been validated and posted and can be seen at https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#geom.
