### ISSUE TITLE
Release B12.1

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#268]
- [x] Update latest software release on nasa-pds.github.io

- [x] Discipline LDD Release
   - [x] [Stage LDD Release](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-StageLDDRelease)
   - [x] [Post Release Updates](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PostReleaseUpdates)

- [x] Deployment of Test Environment
    - [X] DOI Service
    - [X] DOI UI
    - [X] Registry
    - [X] API

- [x] Deployment of Operational Environment
    - [X] DOI Service
    - [X] DOI UI
    - [X] Registry
    - [X] API

- [x] Webpage Updated
   - [x] [Stage IM Release](https://wiki.jpl.nasa.gov/display/PDSEN/PDS4+IM+Release#PDS4IMRelease-StageRelease)
   - [x] Update WebHelp
   - [x] Update TBD web pages

- [x] Released to the Public
   - [x] Send out notification

**Comment by c-suh** [comment]
- [x] update .gitignore and index on 3 machines for the htaccess file mentioned in the staging documentation
- [] create pdsen-ops venv on relevant AWS machines (ran into issues on production machines)
- [ ] (possible) look at script generating LDD page for
   - [ ] old JSON naming of PDS
   - [ ] massaging names to be consistent, e.g. "EBT LDD" to "Earth-Based Telescope"
- [x] update documentation for AWS
- [x] either add SSH keys for AWS machines or update script to use different method of authentication (check in with Jordan). Inelegant but effective method running on gamma.

**Comment by c-suh** [comment]
@viviant100 I've updated the Documents page on gamma such that the links are for the latest documents. However, 3 of the PDFs (Concepts, DPH, and Standards Reference) show markings for the edits. Are these the desired final documents? Another note that we do not yet have the WebHelp pages for ALL.

**Comment by viviant100** [comment]
@c-suh just sent you the docs.

**Comment by tloubrieu-jpl** [comment]
The software summary has been updated on https://nasa-pds.github.io/releases/12.1/index.html

The build 12.1 is made the current release

**Comment by tloubrieu-jpl** [comment]
@jordanpadams and @viviant100 will send the notification email
