### ISSUE TITLE
[ldd-request] Create new LDD "<iras>"

### ISSUE THREAD

**Issue by klopez1313** [NASA-PDS/operations#271]
* **Local Data Dictionary Name:**
The Infrared Astronomical Satellite

* **Namespace ID Requested:**
iras

* **Discipline or Mission LDD?** 
Mission

* **Steward Organization Name:** 
SBN

* **LDD Steward Name:** 
Kristina Lopez

* **LDD Steward Email:** 
klopez@psi.edi

* **LDD Stewardship Team Members:** 
jstone-psi

* **LDD Description:**
The mission dictionary for the IRAS mission that supports the migration of PDS3 keywords into the PDS4 standard

* **Rationale for creation of new LDD:**

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
Hello @klopez1313, and thank you for the submission! In that first comment, please provide the description and rationale as well as the GitHub usernames of any individuals you would like to have on the stewardship team aside from yourself.

**Comment by klopez1313** [comment]
@c-suh thank you!

**Comment by c-suh** [comment]
Namespace requested with Steve at https://github.com/NASA-PDS/pds4-information-model/issues/490.

**Comment by c-suh** [comment]
@klopez1313 and @jstone-psi, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-iras. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started!
