### ISSUE TITLE
Fix citation for Juno MAG CALIBRATED DATA J V1.0, JNO-J-3-FGM-CAL-V1.0

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/operations#279]
## 🐛 Describe the bug

Fix citation in https://pds.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=JNO-J-3-FGM-CAL-V1.0.   

Use https://pds.nasa.gov/datastandards/citing/ as reference to locate the citation (e.g., https://citation.crosscite.org/).  

Per Richard's suggestion,  [doi.org/10.17189/1519711](http://doi.org/10.17189/1519711) -> [Planetary Plasma Interactions Website](https://pds-ppi.igpp.ucla.edu/search/?dataset=JNO-J-3-FGM-CAL-V1.0) -> [CATALOG](https://pds-ppi.igpp.ucla.edu/search/view/?f=yes&id=pds://PPI/JNO-J-3-FGM-CAL-V1.0/CATALOG) -> **_JNO_FGM_J_DS.CAT_** has the correction citation.

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
this looks like this is done
