### ISSUE TITLE
Deploy registry for PPI node

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/operations#282]
In Sook Moon has provided the supporting information to deploy a registry for PPI.

**Comment by jimmie** [comment]
PPI registry has been created and running but waiting on a CCS ticket w/ the SAs (permissions need to be extended) which is preventing access to it from the EN opensearch.

**Comment by tloubrieu-jpl** [comment]
@jimmie should update:
- the wiki with the PPI registry
- pds api doc with new endpoint https://nasa-pds.github.io/pds-api/search-api-user-guide/endpoints.html#endpoints

**Comment by jimmie** [comment]
Wiki updated (https://wiki.jpl.nasa.gov/display/PDSEN/AWS+Node+Registries), PR [pds-api 204](https://github.com/NASA-PDS/pds-api/pull/204) created.

**Comment by jimmie** [comment]
PR has been approved and merged. Closing.
