### ISSUE TITLE
[ldd-release] SPECLIB LDD Version:1.4.0.0 IM Version: 1.18.0.0

### ISSUE THREAD

**Issue by scholes-ds** [NASA-PDS/operations#287]
* **Is the LDD IngestLDD in Github?**  Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?**  Yes

Would be preferred in the next 3 weeks.

* **Need-by date rationale**:
These updates were from the DMSP workshop feedback. It would be nice have the update deployed, since I'm already submitting the results late due to waiting on feedback from data providers. Just let me know if you have questions. Thanks! 

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**: 
* 
* https://github.com/pds-data-dictionaries/ldd-speclib/releases/tag/1I00_1400

* **PDS4 IM version to release with**:
1.18.0.0

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
@scholes-ds you've mastered the release process! The fruit has been posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.18.0.0.shtml#speclib.
