### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:maven_acc (resubmitted)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#289]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[maven_acc_20220802.tar.gz](https://github.com/NASA-PDS/operations/files/9242483/maven_acc_20220802.tar.gz)

* **Validation report**: 
[maven_acc_bundle.txt](https://github.com/NASA-PDS/operations/files/9242489/maven_acc_bundle.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by tinagueth** [comment]
This is a re-submission of MAVEN acc bundle. There were some issues that required fixing, which were done, and it was recommended to re-submit it as it is the final version of this bundle. See #284

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:maven_acc_v1.1_20220801

**Comment by tinagueth** [comment]
@c-suh bundle has been archived
