### ISSUE TITLE
[ldd-request] Create new LDD "apollo"

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#290]
* **Local Data Dictionary Name:**
Apollo

* **Namespace ID Requested:**
apollo

* **Discipline or Mission LDD?** 
mission

* **Steward Organization Name:** 
PDS Geosciences Node

* **LDD Steward Name:** 
Jennifer Ward

* **LDD Steward Email:** 
jgward@wustl.edu

* **LDD Stewardship Team Members:** 
jennifergward, edguinness

* **LDD Description:**
The Apollo Mission Dictionary (apollo) contains classes, attributes and rules specific to the Apollo missions and their instruments.

* **Rationale for creation of new LDD:**
Forthcoming PDS4 migrations and individual data provider submissions.

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
@jennifergward and @edguinness, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-apollo! Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
