### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mars2020_meda (resubmitted)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#292]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[mars2020_meda_20220816.tar.gz](https://github.com/NASA-PDS/operations/files/9352086/mars2020_meda_20220816.tar.gz)

* **Validation report**: 
[meda_bundlev4.txt](https://github.com/NASA-PDS/operations/files/9352092/meda_bundlev4.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by jordanpadams** [comment]
closing as wontfix since this is invalid

**Comment by tinagueth** [comment]
@c-suh re-submission of meda_bundle #293 has been archived
