### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mars2020_meda (updated resubmission)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#293]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[mars2020_meda_20220816v1.tar.gz](https://github.com/NASA-PDS/operations/files/9354266/mars2020_meda_20220816v1.tar.gz)

* **Validation report**: 
[meda_bundlev4.txt](https://github.com/NASA-PDS/operations/files/9354271/meda_bundlev4.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth, a friendly nudge to upgrade your Validate tool to the [latest](https://github.com/NASA-PDS/validate/releases/latest) (currently v2.3.0). Thank you!

---

This set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020_meda_v1.0_20220816

**Comment by tinagueth** [comment]
@c-suh Thank you. I will remind Lyle again to update the Validate tool.

**Comment by smclaughlin7** [comment]
@tinagueth @c-suh Good news re: SIP LID

- urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020_meda_v1.0_20220816

NSSDCA ingest did not detect any issues with this submission. We have successfully ingested all products and are presently archiving to tape.  Thanks to you and Lyle for quickly resolving the previous issues and resubmitting!

**Comment by tinagueth** [comment]
@c-suh meda_bundle has been archived
