### ISSUE TITLE
[lid-request] urn:nasa:pds:lro_diviner_calibrated

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#295]
* **PDS4 LID:**
urn:nasa:pds:lro_diviner_calibrated

* **LID Type:**
Bundle
  
* **Mission:** 
Lunar Reconnaissance Orbiter (LRO)

* **Responsible Node:** 
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
This is approved. Thanks, Jenn.
