### ISSUE TITLE
[doi-request] Submit DOIs for all PDS3 Data Sets

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#3]
We need to get DOI for all PDS3 data sets we have in our registry (with the exception of PSA and Small Bodies Node data sets).

Initial cut at DOI Metadata posted here:
https://github.com/NASA-PDS/pdsen-operations/tree/pds3_dois/dois

Email notification sent to DNs and metadata guidelines posted here: https://pds-engineering.jpl.nasa.gov/content/doi#PDS3%20DOI%20Metadata%20Guidelines 

- [x] ATM
- [x] GEO
- [x] IMG
- [x] PPI
- [x] RMS
- [x] NAIF

See comments below for running status 
---
## Background info

Looks like we can get a majority of this info from the Keyword Search as-is. According to the search results there are ~1441 data sets in our system.

https://pds.nasa.gov/services/search/select?wt=json&rows=1500&q=product_class:Product_Data_Set_PDS3%20AND%20-node_id:psa%20AND%20-node_id:%22small%20bodies%22%20AND%20-node_id:%22planetary%20science%20archive%22&fl=data_set_id,data_set_name,identifier,title,node_id,archive_status,abstract_text,data_set_terse_description,resLocation,start_time,stop_time,data_set_release_date,full_name,citation_description,target_type,investigation_name,instrument_host_id,instrument_host_name,target_name,instrument_name,instrument_id,instrument_type,alternate_id,alternate_title,citation_keyword,

You can run wget to get a CSV of all the records:
```
wget 'https://pds.nasa.gov/services/search/select?wt=csv&rows=1500&q=product_class:Product_Data_Set_PDS3%20AND%20-node_id:psa%20AND%20-node_id:%22small%20bodies%22%20AND%20-node_id:%22planetary%20science%20archive%22&fl=data_set_id,data_set_name,identifier,title,node_id,archive_status,abstract_text,data_set_terse_description,resLocation,start_time,stop_time,data_set_release_date,full_name,citation_description,target_type,investigation_name,instrument_host_id,instrument_host_name,target_name,instrument_name,instrument_id,instrument_type,alternate_id,alternate_title,citation_keyword,' -O pds3_datasets.csv
```

Or you can also get the JSON (which may be easier to parse?):
```
https://pds.nasa.gov/services/search/select?wt=json&rows=1500&q=product_class:Product_Data_Set_PDS3%20AND%20-node_id:psa%20AND%20-node_id:%22small%20bodies%22%20AND%20-node_id:%22planetary%20science%20archive%22&fl=data_set_id,data_set_name,identifier,title,node_id,archive_status,abstract_text,data_set_terse_description,resLocation,start_time,stop_time,data_set_release_date,full_name,citation_description,target_type,investigation_name,instrument_host_id,instrument_host_name,target_name,instrument_name,instrument_id,instrument_type,alternate_id,alternate_title,citation_keyword,' -O pds3_datasets.json
```

Or XML (which may be easier to parse?):
```
wget 'https://pds.nasa.gov/services/search/select?wt=xml&rows=1500&q=product_class:Product_Data_Set_PDS3%20AND%20-node_id:psa%20AND%20-node_id:%22small%20bodies%22%20AND%20-node_id:%22planetary%20science%20archive%22&fl=data_set_id,data_set_name,identifier,title,node_id,archive_status,abstract_text,data_set_terse_description,resLocation,start_time,stop_time,data_set_release_date,full_name,citation_description,target_type,investigation_name,instrument_host_id,instrument_host_name,target_name,instrument_name,instrument_id,instrument_type,alternate_id,alternate_title,citation_keyword' -O pds3_datasets.xml
```

Here is are test CSV, JSON, XML with only 50 records in each to make testing a bit easier/faster:
XML: [pds3_datasets_20200612.xml.txt](https://github.jpl.nasa.gov/PDSEN/ops/files/7652/pds3_datasets_20200612.xml.txt)
JSON: [pds3_datasets_20200612.json.txt](https://github.jpl.nasa.gov/PDSEN/ops/files/7653/pds3_datasets_20200612.json.txt)
CSV: [pds3_datasets_20200612.csv.txt](https://github.jpl.nasa.gov/PDSEN/ops/files/7654/pds3_datasets_20200612.csv.txt)

These are pretty much all the fields we have available through search, but there may be more in the Registry if these are not sufficient.

The output does include a node_id field as well which we can map to the appropriate node in the DOI metadata:

```
node_id: [
"planetary plasma interactions",
459,
"geosciences",
353,
"planetary atmospheres",
290,
"imaging",
262,
"navigation and ancillary information facility",
27,
"planetary rings",
23,
"engineering",
2,
"radio science",
1
]
```

If we want to narrow on `archive_status`, I can also try to do that if there are specific statuses we want to filter out.

**Comment by jordanpadams** [comment]
GEO Submission includes txt with DataSets not getting DOIs, and the DOI metadata.

[geo_pds3_dois.zip](https://github.com/NASA-PDS/pdsen-operations/files/5284230/geo_pds3_dois.zip)

**Comment by jordanpadams** [comment]
From PPI:

[DOI_PPI_registered_all_records-revised-201001.txt](https://github.com/NASA-PDS/pdsen-operations/files/5319852/DOI_PPI_registered_all_records-revised-201001.txt)
[DOI_PPI_registered_all_records-sorted_jp.xlsx](https://github.com/NASA-PDS/pdsen-operations/files/5319853/DOI_PPI_registered_all_records-sorted_jp.xlsx)

4 SBN DataSets sent to SBN - **per Anne R., these will be forwarded to SBN-PSI for acquiring DOIs**:
GO-A-UVS-2-EDR-V1.0
GO-A-UVS-3-RDR-V1.0
GO-D-GDDS-5-DUST-V3.0
ULY-D-UDDS-5-DUST-V1.1

3 GEO DataSets set to GEO - **per Jennifer W., these are planned for migration and do not need DOIs for PDS3**:
LP-L-ENG-6-ATTITUDE-V1.0
LP-L-ENG-6-COMMAND-V1.0
LP-L-ENG-6-SUNPULSE-V1.0

**Comment by tloubrieu-jpl** [comment]
@jordanpadams should I move this issue to the next sprint ? Thanks

**Comment by jordanpadams** [comment]
yes. TBD waiting on additional DNs to submit

**Comment by jordanpadams** [comment]
NAIF: [DOI_NAIF_registered_all_records_201012_naif.xml.txt](https://github.com/NASA-PDS/pdsen-operations/files/5367036/DOI_NAIF_registered_all_records_201012_naif.xml.txt)

> I removed the following 7 data sets from it:
> 
>     ESA data sets:
> 
>        ROS-E/M/A/C-SPICE-6-V1.0         (NOTE: superseded)
>        RO/RL-E/M/A/C-SPICE-6-V1.0
>        VEX-E/V-SPICE-6-V1.0             (NOTE: will be superseded soon)
>        MEX-E/M-SPICE-6-V1.0             (NOTE: will be superseded soon)
> 
>     JAXA data sets:
> 
>        VCO-V-SPICE-6-V1.0
> 
>     Other nodes', non-SPICE data sets
> 
>        MESS-E/V/H-GRNS-3-NS-CDR-V2.0
>        MESS-E/V/H-GRNS-4-NS-DDR-V2.0

Sent MESS-* data sets to GEO for review: https://github.com/NASA-PDS/pdsen-operations/blob/pds3_dois/dois/DOI_GEO_additional_20201012.xml

**Comment by jordanpadams** [comment]
from GEO:
```
We compared our list of PDS3 DOIs with our holdings list, and found some additional datasets for which we’d like DOIs. These were all missing from the original metadata XML for some reason.
 
Attached are the following scrubbed PDS3 dataset catalog files. Please acquire DOIs. Let me know if you don’t see the attachment- JPL likes to reject my ZIP files.
A15A-L-HFE-3-THERMAL-CONDUCTIVITY-V1.0
A17A-L-HFE-3-THERMAL-CONDUCTIVITY-V1.0
CLEM1-L-RSS-5-GRAVITY-V1.0
GSSR-M-RTLS-5-ALT-V1.0
KAGUYA-L-SP-5-SPECTRA-V1.0
MGS-M-MOLA-5-SHADR-V1.0
MRO-M-CRISM-4-TYPESPEC-V1.0
MSL-M-SAM-3-RDR-L1A-V1.0
 
Additionally, we’ve attached the following scrubbed PDS3 dataset catalog files. However, these datasets are also located at another node, so it’s possible they were included in the other node’s XML, and that DOIs were already acquired for them. I assume you have some way of checking this.
MGS-M-RSS-5-SDP-V1.0 [Atmospheres or PPI]
NEAR-A-NLR-5-CDR-EROS/ORBIT-V1.0 [SBN]
NEAR-A-NLR-6-EROS-MAPS-MODELS-V1.0 [SBN]
VL1/VL2-M-LCS-2-EDR-V1.0 [Imaging]
VO1/VO2-M-VIS-2-EDR-V2.0 [Imaging]
 
This one appears to not have been registered, so I guess that needs to happen before we can get a DOI.
VL2-M-SEIS-5-RDR-V1.0
 
This one is registered, but I can’t find a catalog file for it. Can a DOI be acquired using the registered information?
FEXP-E-SHYG-3-RDR-OPT-DEP-V1.0
 
And finally, this one is not registered and does not have a catalog file. However, other datasets from the same sampler CD are registered. Hopefully we can get a DOI for this one somehow.
MGS-M-MOC-4-SAMPLER-V1.0
```

**Comment by jordanpadams** [comment]
From IMG: 
[DOI_IMG_registered_all_records_Oct28_2020.xml.txt](https://github.com/NASA-PDS/pdsen-operations/files/5449197/DOI_IMG_registered_all_records_Oct28_2020.xml.txt)

**Comment by jordanpadams** [comment]
removed delayed labels since this is an ongoing LOE task

**Comment by jordanpadams** [comment]
LRO data sets added by GEO: https://github.com/NASA-PDS/pdsen-operations/blob/pds3_dois/dois/DOI_GEO_registered_all_records_lro.xml
