### ISSUE TITLE
Validate and Upload PDS3 Standards Collection

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/operations#305]
## 💡 Description

- [x] Validate PDS3 standard collections in the zip file (LFT)
- [x] Create a new directory "document_pds3_standards" under https://pds.nasa.gov/data/pds4/documents/
- [x] Upload PDS3 standard collections to https://pds.nasa.gov/data/pds4/documents/document_pds3_standards

**Comment by c-suh** [comment]
Files have been validated and a few of the errors are being worked on. Waiting to receive reworked files.

**Comment by c-suh** [comment]
Received reworked files but a new error appeared when validating. Sent an email to Vivian, who passed it along to Ron.

**Comment by viviant100** [comment]
@c-suh please go ahead and post.  We do not convert the docs to PDF/A.

**Comment by c-suh** [comment]
@viviant100 these have been posted to https://pds.nasa.gov/data/pds4/documents/document_pds3_standards/! Please let me know if anything looks amiss.

**Comment by viviant100** [comment]
All good, thanks @c-suh!
