### ISSUE TITLE
[ldd-request] Create new LDD "<proposed namespace ID>"

### ISSUE THREAD

**Issue by toufikazizi1** [NASA-PDS/operations#311]
)
  -

**Comment by c-suh** [comment]
Hello @toufikazizi1! I don't believe we have met before; which organization do you hail from? Let me know if you would like assistance with this request!

**Comment by c-suh** [comment]
@toufikazizi1 I am closing this request. Please let me know if you would like to revisit the issue. Happy early holidays!
