### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mgs_tes_recalib_atmos (resubmission)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#321]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[mgs_tes_recalib_20221213.tar.gz](https://github.com/NASA-PDS/operations/files/10229022/mgs_tes_recalib_20221213.tar.gz)

* **Validation report**: 
[mgs_tes_recalib_atmosv2_1.txt](https://github.com/NASA-PDS/operations/files/10229026/mgs_tes_recalib_atmosv2_1.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:mgs_tes_recalib_atmos_v2.0_20221213

**Comment by tinagueth** [comment]
@c-suh The AIP/SIP set for this resubmitted bundle has been archived (and as mentioned in the other issue, I closed the original submission for this particular bundle as the resubmission was accepted and archived)
