### ISSUE TITLE
[nssdca-delivery] em16_spice, insight.spice, mars2020.spice, maven.spice, vco_spice

### ISSUE THREAD

**Issue by alyssambailey** [NASA-PDS/operations#322]
### Discipline Node Information

This delivery consists of 15 SPICE Bundle releases for EM16, Insight, Mars2020, MAVEN, and VCO.

* **Delivering Node**: NAIF 

* **NSSDCA Delivery Package**: https://naif.jpl.nasa.gov/pub/naif/pds/misc/nssdca/pds4/202212/

* **Validation report**: Validate version 1.8.0 was used to validate em16, insight, mars2020, maven and 2.3.0 was used to validate vco. 
[validation_reports_naif.tar.gz](https://github.com/NASA-PDS/operations/files/10281468/validation_reports_naif.tar.gz)

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
Hello @alyssambailey and thank you for your submission! A few notes:
- When running the Validate tool on these bundles, a rule must be specified with`-R pds4.bundle`. The validation reports show that all except the VCO bundle are missing this. Please refer to [Validation Rules](https://nasa-pds.github.io/validate/operate/index.html#Validation_Rules) for more information.
- Please create and submit a validate report for each bundle. Currently, there is only one report per instrument for the latest version of each bundle, but Validate can be run on each version of each bundle (for a total of 15 reports for the 15 bundles).
- I appreciate your note about the Validate tool versions which were used! However, I strongly, strongly recommend upgrading to the [latest version](https://github.com/NASA-PDS/validate/releases/latest) as you are currently missing all improvements and bug fixes from two major versions releases (v1.8.0 versus latest v3.1.1). If needed, the [Installation instructions](https://nasa-pds.github.io/validate/install/index.html) provide helpful reminders of configuration settings that may also need to be updated. 
- For future submissions, please package the bundles into a single tarball or zip for easy download (such as you did with the multiple validation reports) or change the website or webpage settings on your provided link for the packages to allow `wget` or `curl` of the multiple files. 

Please let me know if you have any questions or concerns. Thank you!

---

One bundle (VCO) was validated with a relatively recent version of the Validate tool as well as used the correct validation rule (-R pds4.bundle), so I have posted this for NSSDCA processing. You can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:vco_spice_v1.0_20221221

**Comment by smclaughlin7** [comment]
@c-suh Happy 2023!  Our SIP auto-puller appears to have been offline last night, so it did not pull this SIP/Deep Archive package:

SIP LID:  urn:nasa:pds:system_bundle:product_sip_deep_archive:vco_spice_v1.0_20221221

This is good because our front-end would have rejected it because the <manifest_URL> specified in https://pds.nasa.gov/data/pds4/manifests/2023/vco_spice_v1.0_20221221_sip_v1.0.xml is

https://pds.nasa.gov/data/pds4/manifests/2022/vco_spice_v1.0_20221221_sip_v1.0.tab

but this file is posted in the 2023 subdirectory

https://pds.nasa.gov/data/pds4/manifests/2023/vco_spice_v1.0_20221221_sip_v1.0.tab

Since this SIP package generated in 2022, could you please move it to the 2022 subdirectory?   Otherwise @alyssambailey would have to regenerate and resubmit a new SIP/Deep Archive package for the VCO SPICE bundle to update the <manifest_URL> to specify the 2023 subdirectory.

Thanks!

**Comment by c-suh** [comment]
Hello @smclaughlin7 and happy 2023! Ironically following that greeting - thwarted once again by the changing of the year. I imagine this won't happen often, but I'll update our script to post to the year subdirectory specified in the <manifest_URL>. In the meantime, I've moved those vco_spice files to the 2022 directory. Thank you for catching this and for the fast communication!

**Comment by smclaughlin7** [comment]
@c-suh Thanks for moving that SIP package so quickly!  I actually forgot the package needs to be posted in the online year subdirectory that matches the year subdirectory specified in the <manifest_URL>.  I just happened to notice this morning, after realizing our SIP auto-puller didn't run last night because of a connectivity issue.  We got lucky! Our SIP auto-puller should download this SIP tonight.   @alyssambailey

**Comment by c-suh** [comment]
@smclaughlin7 yup, I forgot the reason for the year subdirectories, too. Here's to luck!

**Comment by alyssambailey** [comment]
Thanks @smclaughlin7 !

Hi @c-suh,

I downloaded the latest validate, ran each version with -R pds4.bundle, and have included an updated tar with those 14 validation reports for EM16, InSight, MAVEN, and Mars2020. I have added your note regarding future submissions to my notes for next time!

[validation_reports_em16_insight_mars2020_maven_naif.tar.gz](https://github.com/NASA-PDS/operations/files/10364751/validation_reports_em16_insight_mars2020_maven_naif.tar.gz)


EM16 has some failures due to carriage returns which were not an issue for older versions of validate. The carriage return issue was fixed for release 6. 
MAVEN has a failure related to release 27 checksum file size which was not caught with older versions of validate and MAVEN release 27 was processed by NSSDCA on 2021-12-21. 

Please let me know if you have any issues with what I have provided!

Thanks!

**Comment by smclaughlin7** [comment]
@c-suh @alyssambailey  Good news:  The NSSDCA received and is processing the VCO SPICE submission. You can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:

- urn:nasa:pds:system_bundle:product_sip_deep_archive:vco_spice_v1.0_20221221

**Comment by c-suh** [comment]
@alyssambailey thank you very much for updating validate and re-running it on each version with the rule! I also appreciate the explanations regarding the EM16 and MAVEN failures as they are pertinent to the reported errors. Before I post the remaining 14 packages for NSSDCA processing, would you like to review them for floating, misplaced, or missing files? Each report has at least one `warning.file.not_referenced_in_label` and a number of `warning.integrity.unreferenced_member`s.

**Comment by alyssambailey** [comment]
@c-suh there are no floating, misplaced, or missing files - they are ready for you to post! Thanks!

**Comment by c-suh** [comment]
@alyssambailey very well! These 14 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v4.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v5.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v6.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v11.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v12.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v13.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v14.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v3.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v4.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v5.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v28.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v29.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v30.0_20221221
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v31.0_20221221

---

@smclaughlin7 thank you for the update on the first VCO SPICE submission. Hopefully these others go through just as smoothly!

**Comment by oddes** [comment]
Validated on 11/11/2023: SIP is successfully archived
