### ISSUE TITLE
[ldd-request] Create new LDD "SBN"

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/operations#323]
* **Local Data Dictionary Name:**
Small Bodies Node Dictionary

* **Namespace ID Requested:**
sbn

* **Discipline or Mission LDD?** 
Discipline

* **Steward Organization Name:** 
SBN (SBNUMD for now)

* **LDD Steward Name:** 
Anne Raugh

* **LDD Steward Email:** 
araugh@umd.edu

* **LDD Stewardship Team Members:** 
acraugh

* **LDD Description:**
This dictionary will provide classes to support the documentation, support, discovery, and reuse of data from, by, and for small bodies research.

* **Rationale for creation of new LDD:**
As I work on migrating SB data from missions, space telescopes, and groundbased sources, it seems that the small bodies community has a very different view from other PDS user communities of the how to process and document image data, and what metadata is essential for discovery and reuse. SB-related data processing and analysis also seems to involve situations that do not appear to recur at other nodes - or they would already be present  as options in existing discipline dictionaries like img: and proc:.  SBN does not have sufficient personnel to add people to several other steward teams even if it were likely those stewards would be willing to introduce potentially breaking changes to their dictionaries, nor the calendar time at this point to wait until there is a formal design and configuration control process established for discipline dictionaries. In order to be able to complete migration of high-priority data sets on schedule and better support data coming in from PDS4 missions, the necessary support will be designed and created within the SBN namespace following established conventions as far as possible where they exist, and small bodies conventions where those differ from existing conventions in other discipline dictionaries.

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by jordanpadams** [comment]
@acraugh your new repo is ready here: https://github.com/pds-data-dictionaries/ldd-sbn
