### ISSUE TITLE
[lid-request] urn:nasa:pds:ltb_hvm3_prp

### ISSUE THREAD

**Issue by dvpolitte** [NASA-PDS/operations#325]
* **PDS4 LID:** urn:nasa:pds:ltb_hvm3_prp

* **LID Type:** Bundle
  
* **Mission:** Lunar Trailblazer

* **Responsible Node:** GEO

Note: this LID replaces the LID urn:nasa:pds:ltb_hvm3_loi, which GEO previously reserved. Please remove that LID from the database. (It was never used by the mission in practice and never will be.)

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Please proceed. This bundle LID and ...:ltb_ltm_prp  look fine to me, and there's no conflict. I'll register them after we finish a migration to wordpress

**Comment by rchenatjpl** [comment]
Thanks, Daniel, both actions are complete.
