### ISSUE TITLE
[lid-request] urn:nasa:pds:ltb_ltm_prp

### ISSUE THREAD

**Issue by dvpolitte** [NASA-PDS/operations#326]
* **PDS4 LID:** urn:nasa:pds:ltb_ltm_prp

* **LID Type:** Bundle
  
* **Mission:** Lunar Trailblazer

* **Responsible Node:** GEO

Note: this LID replaces the LID urn:nasa:pds:ltb_ltm_loi, which GEO previously reserved. Please remove that LID from the database. (It was never used by the mission in practice and never will be.)

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Thanks, Daniel, both these actions are complete.
