### ISSUE TITLE
[lid-request] urn:nasa:pds:lro_diviner_raw

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#330]
* **PDS4 LID:**
urn:nasa:pds:lro_diviner_raw

* **LID Type:**
Bundle
  
* **Mission:**
Lunar Reconnaissance Orbiter (LRO)

* **Responsible Node:**
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Please proceed. The bundle LID looks fine to me, and there's no conflict. I'll register it after we finish a migration to wordpress

**Comment by jordanpadams** [comment]
@rchenatjpl any status here?

**Comment by rchenatjpl** [comment]
cr@p, I forgot to close this. I hope I didn't forget to tell @jennifergward. The bundle is coming in the next delivery in any case.
