### ISSUE TITLE
[lid-request] urn:nasa:pds:libs_reference_database

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#331]
* **PDS4 LID:**
urn:nasa:pds:libs_reference_database

* **LID Type:**
Bundle
  
* **Mission:**
N/A

* **Responsible Node:**
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
done. thanks
