### ISSUE TITLE
[ldd-request] Create new LDD "<lucy>"

### ISSUE THREAD

**Issue by katecrombie** [NASA-PDS/operations#334]
* **Local Data Dictionary Name:**
The Lucy Mission Local Data Dictionary

* **Namespace ID Requested:**
lucy

* **Discipline or Mission LDD?** 
This is a mission LDD request

* **Steward Organization Name:** 
PDS SBN (Maryland)

* **LDD Steward Name:** 
Michael S.P. Kelley - PDS Contact
Kate Crombie - Lucy Mission Contact

* **LDD Steward Email:** 
msk@astro.umd.edu
crombie@indigoinfos.com

* **LDD Stewardship Team Members:** 
katecrombie

* **LDD Description:**
This LDD is the Lucy Mission LDD. It is used to describe and enumerate Lucy Mission specific classes and attributes. It also includes Lucy Instrumentation specific classes and attributes.

* **Rationale for creation of new LDD:**
This LDD is needed to describe the specifics of both the Lucy Mission and the instrumentation on board the Lucy spacecraft.

---

**Engineering Details**
- [x] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
@katecrombie, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-lucy ! Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
