### ISSUE TITLE
Review telecon archive pages

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/operations#340]

**Comment by rchenatjpl** [comment]
sorry, where are these pages?

**Comment by viviant100** [comment]
@rchenatjpl  here it is: https://docs.google.com/spreadsheets/d/1uEgY0wH9nStMOvN0hBFTSMA53srgx-OUDBAm38IOYpg/edit#gid=1986925317&range=A130:M245.   Since Colleen is working her way top-down of those same pages, you can start from the bottom (down-up) of those pages (so, from row 245) per csuh suggestion.

**Comment by c-suh** [comment]
Results put into the Google spreadsheet linked above, addressed in https://github.com/NASA-PDS/operations/issues/348, and are being re-reviewed. This task of initially reviewing these pages is complete.
