### ISSUE TITLE
[ldd-release] ldd-hyb2  LDD Version: 1200 IM Version: 1E00

### ISSUE THREAD

**Issue by neese** [NASA-PDS/operations#341]
* **Is the LDD IngestLDD in Github?** _Yes or no_ Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** _Yes or no_ Yes

* **Need-by date**:  Needed to support data already archived, so as soon as reasonable.

* **Need-by date rationale**:  The dictionary was ready in GitHub for the December 2022 build deadline, but was not picked up for publication at that time.  I think it may be because it is a mission dictionary, and only discipline dictionaries are included in the nominal build schedule releases?  In any case it is now much later than we intended.  Data have already been released in the archive which depend on this ldd.

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**:  https://github.com/pds-data-dictionaries/ldd-hyb2

* **PDS4 IM version to release with**: 1E00

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
@jordanpadams I tried to tag a release for this dictionary (Hyb2 1E00 1200) by following the steps at https://pds-data-dictionaries.github.io/development/ldd-release.html#tag-a-release-in-github, but it didn't trigger a GitHub Action. Has the procedure changed? Should I just post these files without a tagged release?

**Comment by jordanpadams** [comment]
@c-suh looks like I updated the Github Action to only run when files in the `src` directory change, not realizing I broke those instructions.

I [updated the docs](https://pds-data-dictionaries.github.io/development/ldd-release.html#tag-a-release-in-github) and manually triggered per the new procedure.

**Comment by jordanpadams** [comment]
@c-suh @neese tagging complete: https://github.com/pds-data-dictionaries/ldd-hyb2/releases

**Comment by jordanpadams** [comment]
@neese per this comment:

> The dictionary was ready in GitHub for the December 2022 build deadline, but was not picked up for publication at that time. I think it may be because it is a mission dictionary, and only discipline dictionaries are included in the nominal build schedule releases?

that is correct. for mission LDDs, it is the responsibility of the steward to [manually trigger the release](https://pds-data-dictionaries.github.io/development/ldd-release.html#tag-a-release-in-github). sorry for the confusion.

**Comment by jordanpadams** [comment]
@neese you are good on the ticket. @c-suh will take it from here.

the docs [have been updated](https://github.com/pds-data-dictionaries/PDS-Data-Dictionaries.github.io/pull/26/) with a new [Mission LDDs page](https://pds-data-dictionaries.github.io/development/mission-ldds.html). additionally, we are always open to any proposed updates. feel free to create a pull request at any time for the docs here: https://github.com/pds-data-dictionaries/PDS-Data-Dictionaries.github.io

**Comment by neese** [comment]
@jordanpadams Thanks!

**Comment by c-suh** [comment]
@neese this LDD has been posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#hyb2 !
