### ISSUE TITLE
Install PDS app bar into WordPress PDS Engineering site

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#342]
The black bar at the top of the page which has the dropdown of nodes

**Comment by jordanpadams** [comment]
@c-suh same thing goes for this app bar as the feedback widget. don't spend too much time

**Comment by c-suh** [comment]
SAs installed plugin, and I installed the PDS app bar with Option 1 of its [README](https://github.com/NASA-PDS/wds-web/tree/main/app-bar).
