### ISSUE TITLE
Install Feedback widget in WordPress PDS Engineering site

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#343]

**Comment by jordanpadams** [comment]
@c-suh not sure if this is an easy task or not, but don't spend much time on this. we will have a new feedback widget once we move to the new design

**Comment by c-suh** [comment]
Tested basics locally (wordpress hook and appearance) and asked SAs to install it.

**Comment by c-suh** [comment]
Have it working locally and have re-requested for SAs to install it.

**Comment by c-suh** [comment]
SAs have reinstalled, and I've sent a test submission through the widget and am waiting to hear if it's gone through.

**Comment by c-suh** [comment]
Success!
