### ISSUE TITLE
deploy registry tools in production

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/operations#346]

**Comment by c-suh** [comment]
@tloubrieu-jpl Registry Manager v4.5.4 and Standalone Harvest v3.7.4 have been deployed to the first production machine with the usual user account. Do these need to be tested and verified in order to close this ticket?

**Comment by viviant100** [comment]
@c-suh Let's test and verify before closing this ticket.  Do we have equivalent ticket for this on gamma?

**Comment by c-suh** [comment]
@viviant100 not quite an equivalent ticket, no. It's in [the description](https://github.com/NASA-PDS/software-issues-repo/issues/40) of an epic but doesn't have its own ticket like this one does. [Here](https://github.com/NASA-PDS/software-issues-repo/issues/40#issuecomment-1411069005) is my comment about that specific task (for gamma).

**Comment by viviant100** [comment]
Thanks @c-suh.  Looks like we haven't verified on gamma either.  Let's make sure both venues are tested.

**Comment by tloubrieu-jpl** [comment]
@rchenatjpl can you test the deployment in gamma and production 1 and 2 ?

**Comment by tloubrieu-jpl** [comment]
The tools are deployed on production 1 and 2.

The documentation on the deployment is on the internal JPL wiki.

**Comment by rchenatjpl** [comment]
@tloubrieu-jpl @jimmie 
Sorry, I can't keep track of the various web pages and endpoints. I want to
1) see what's in the registry before I begin
2) harvest into the registry 
3) check the registry again

So, what are the URLs for the 3 registries? When I tested a long time ago, prod1 was at
https://search-en-prod-di7dor7quy7qwv3husi2wt5tde.us-west-2.es.amazonaws.com
Is that still right? If so, I see a bunch of context products and EN documents already there, so I don't know what more I'd test.
What are the URLs for the registries on prod2 and gamma?
Thanks

**Comment by tloubrieu-jpl** [comment]
Hi @rchenatjpl ,

The urls for the registries are on this web page: https://github.com/NASA-PDS/registry/wiki/Registry-Workshop-06_28_2022

But this is missing the EN tests servers, so I usually go to the AWS console to see the URLs. I don't believe the latest is a bad solution, if you know and are authorized to do it.

@viviant100 @jimmie @jordanpadams any better idea for Richard ?

**Comment by viviant100** [comment]
We have a wiki page with registry URL here: https://wiki.jpl.nasa.gov/display/PDSEN/AWS+Node+Registries

**Comment by jordanpadams** [comment]
this has been completed
