### ISSUE TITLE
Request for version 1G00_1B00 for Rings LDD

### ISSUE THREAD

**Issue by mace-space** [NASA-PDS/operations#352]
* **Is the LDD IngestLDD in Github?** 
 I don't think the IngestLDD for past version PDS4_RINGS_1G00_1B00 is available, looking at https://github.com/pds-data-dictionaries/ldd-rings/commits/main/src/PDS4_RINGS_IngestLDD.xml. (Related to this issue: https://github.com/pds-data-dictionaries/PDS4-LDD-Issue-Repo/issues/235).

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** 
Yes

* **Need-by date**:
March 2023

* **Need-by date rationale**:
An R&A data provider requires version 1G00_1B00 of the rings dictionary to be made available at https://pds.nasa.gov/datastandards/dictionaries. I can find 1G00_1A00 at https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#rings, but I cannot find 1G00_1B00.
The version is already built at https://github.com/pds-data-dictionaries/ldd-rings/tree/main/build/release/1.16.0.0, but when I try to run the Validate tool on the R&A data provider's bundle, there is an error:
 Error occurred while loading schematron: Schematron 'https://pds.nasa.gov/pds4/rings/v1/PDS4_RINGS_1G00_1B00.sch' error: Cannot read schematron from URL https://pds.nasa.gov/pds4/rings/v1/PDS4_RINGS_1G00_1B00.sch

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**:
https://github.com/pds-data-dictionaries/ldd-rings/tree/main/build/release/1.16.0.0/

* **PDS4 IM version to release with**:
1.16
_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: PDS4_RINGS_1G00_1B00
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
@mace-space - the LDD for 1G00_1B00 has been validated and is now available at https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#rings!

**Comment by mace-space** [comment]
Thanks very much!
