### ISSUE TITLE
Remove OSTI from DOI reference doc

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/operations#354]
## 💡 Description
Per Ron's email on OSTI DOI:

(1) I suggest a rewrite of some of the sections in the following web pages:
          -- remove all references to OSTI and the OSTI service
 
>> https://pds-engineering.jpl.nasa.gov/content/doi#update
>> https://pds-engineering.jpl.nasa.gov/content/doi#pds3_dois
 
(2)  https://pds-engineering.jpl.nasa.gov/content/doi#update
           -- remove Option 2.
 
(3) https://pds-engineering.jpl.nasa.gov/content/doi#Introduction
          -- Suggest removing or rewriting this sentence:
                   -- The DOIs are maintained by external partners: PDS DOIs are created through [OSTI](https://www.osti.gov/data-services) service and registered at [DataCite](https://datacite.org/).
 
(4)  Suggest removing this section:
 
External OSTI/IAD interface

OSTI/IAD is the partner used by PDS to get DOIs. OSTI/IAD provides a web API for this interface. OST/IAD works with dataCite to maintain the catalogue of DOIs.

PDS’s OSTI contact at is given on https://github.com/NASA-PDS/doi-service/blob/master/docs/operations/OSTI.md

 

(5) Suggest updating Figure in “Processes for Reserving or Releasing a DOI”

      -- replace OST/IAD with either DataCite or DOI Repository

 

(6) Page not found:

       -- Complete the spreadsheet [spreadsheet template](https://pds-engineering.jpl.nasa.gov/sites/default/files/DOI_reserve_template.xlsx), one line per requested DOI
      >> https://pds-engineering.jpl.nasa.gov/sites/default/files/DOI_reserve_template.xlsx
Page not found
 
(7) Suggest rewrite of this section.
         -- remove this sentence:  The Engineering Node Operator will generate an OSTI DOI label that will be proposed to the Discipline Node Requestor for review.
         -- rewrite this sentence from:   When the OSTI DOI label is validated, the Engineering Node Operator submits it at OSTI for release.
                                                        To:   Once the DOI label has been properly validated, the Engineering Node submits the DOI label for “release”.

**Comment by viviant100** [comment]
@c-suh Please see the comments below:

(1) Slide 5 of the doi-accumulating-data-doiwg-220224.ppt shows an example of a XLS that WAS used to request an update to DOI metadata. The “update” function no longer exists.

(2) For "<accession_number>" section:

```
- first, we want to verify if the data set was an international collaboration led by ESA, therefore ESA will be getting a DOI for that data set (after a quick look, this looks to mostly applies to MEX, Rosetta, and VEX data sets). check at https://www.cosmos.esa.int/web/esdc/doi/planetary.
- Next, if possible, we would like to do a basic count check to ensure the number of data sets we have in our database match with your PDS3 data set count:
  - IMG: 262
  - ENG: 2
  - PPI: 588
  - RINGS: 23
  - ATMOS: 279
  - NAIF: 28
  - GEO: 317

```

-  <accession_number> was a construct of OSTI and is not applicable to DataCite.
- Per Ron's comment, it's not clear why the PDS3 data set count is here?  Perhaps @jordanpadams knows?

**Comment by c-suh** [comment]
@jordanpadams regarding (2) in the comment above, remove the entire "<access_number>" bullet under the Required section? Or does the sub-bullet about the PDS3 data set count need to remain and, if so, where?

@viviant100 I'm not sure what to do about (1). Do I reach out to Joe Mafi and ask him to edit slide 5 so that it matches the information [here](https://pds-engineering.jpl.nasa.gov/content/doi#update)? If I edit it myself (after obtaining permission from Joe Mafi), should that be noted on the slide, that it was edited by another person/PDS Engineering, Operations?

**Comment by jordanpadams** [comment]
@c-suh @viviant100 removed the part for (2) and updated the powerpoint.

[doi-accumulating-data-doiwg-230217.pptx](https://github.com/NASA-PDS/operations/files/10771540/doi-accumulating-data-doiwg-230217.pptx)

**Comment by c-suh** [comment]
Great; thank you! I uploaded the powerpoint and updated the link on the DOI page (last sentence before the diagram in [this section](https://pds-engineering.jpl.nasa.gov/content/doi#accumulating-guidelines)). @viviant100, please let me know if there are more comments or if this issue can be closed.

**Comment by c-suh** [comment]
No further feedback. Vivian confirmed this is good to close.
