### ISSUE TITLE
[lid-request] urn:nasa:pds:msl_apxs_raw, urn:nasa:pds:msl_apxs_calibrated

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#356]
* **PDS4 LID:** 
urn:nasa:pds:msl_apxs_raw
urn:nasa:pds:msl_apxs_calibrated

* **LID Type:** 
Bundle
  
* **Mission:** 
MSL

* **Responsible Node:** 
GEO
---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
done. thanks
