### ISSUE TITLE
[ldd-release] OREX  LDD Version: 1500  IM Version: 1700

### ISSUE THREAD

**Issue by neese** [NASA-PDS/operations#357]
* **Is the LDD IngestLDD in Github?** _Yes or no_ No

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** _Yes or no_ Yes

* **Need-by date**:  As soon as convenient

* **Need-by date rationale**:  The mission LDD update and the bundle referencing it were submitted to us at the same time, and the bundle is now being archived. It would be good to get the LDD ingested soon to support the bundle.

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**:

* **PDS4 IM version to release with**:

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_ PDS4_OREX_1700_1500
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_ orex_1700_1500.zip
    * .xsd – XML Schema file
    * .sch – Schematron file
[orex_1700_1500.zip](https://github.com/NASA-PDS/operations/files/10806485/orex_1700_1500.zip)

    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by c-suh** [comment]
@neese, the LDD files for OREX 1700 1500 have been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#orex.

**Comment by neese** [comment]
@c-suh Wow, that was fast.  Thanks!
