### ISSUE TITLE
Add registry-loader tools into ops procedures

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#359]
## 💡 Description

This only applies to system bundle updates (context products, SIPs, PDS-wide documents, something else?)

**Comment by jordanpadams** [comment]
@viviant100 adding you as an assignee as well to be able to report on this at team meetings

**Comment by viviant100** [comment]
Per @rchenatjpl slack message, here are the wiki pages for the products:

1. [Context Product Ingestion](https://wiki.jpl.nasa.gov/display/PDSEN/Context+Product+Ingestion)
2. [Tool Registry Ingestion](https://wiki.jpl.nasa.gov/display/PDSEN/Tool+Registry+Ingestion)
3. [(Product_) Bundle, Collection, and Document Ingestion](https://wiki.jpl.nasa.gov/display/PDSEN/%28Product_%29+Bundle%2C+Collection%2C+and+Document+Ingestion)
4. [PDS4 Data Release at EN](https://wiki.jpl.nasa.gov/display/PDSEN/2.+PDS4+Data+Release+at+EN)

**Comment by rchenatjpl** [comment]
Is this what's desired? https://wiki.jpl.nasa.gov/display/PDSEN/EN%27s+Ingestion+into+the+OpenSearch+registry
