### ISSUE TITLE
Improve Left Navigation Pane

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#361]
It's currently too long. Options:

1. remove second levels
2. reorganize site structure
3. make dropdowns like current Drupal site

I have opted for option 3. For option 1, not every 1st level page has links to the second level pages, so it'd be too difficult to find those if they are not in the navigation. Option 2 is potentially a large undertaking, even for temporary measures (e.g. simplify and group the first level pages). Option 3, while not desirable in that we must eventually get rid of the left navigation pane, stays within the current scope of the work of moving the PDS Engineering site, as is, from Drupal to WordPress; improving the usability and integrating the web modernization features are entirely another beast.

**Comment by c-suh** [comment]
@jordanpadams and @viviant100 the left navigation pane has toggleable levels as well as a mobile version of the menu. Please review and let me know your thoughts. Thank you!

**Comment by jordanpadams** [comment]
@c-suh looks great! is there any way we can change the background color for the opened tabs? it seems a bit hard to read and may not be appropriately accessible.

**Comment by c-suh** [comment]
@jordanpadams yes, thank you for the reminder! I adjusted the style and placement of the opened tabs (the subnav) and also adjusted the text color on hover for all nav items so that it passes this [contrast checker](https://webaim.org/resources/contrastchecker/). Please take another look and let me know.

**Comment by jordanpadams** [comment]
looks great. thanks @c-suh
