### ISSUE TITLE
[ldd-request] Create new LDD "psyche"

### ISSUE THREAD

**Issue by neese** [NASA-PDS/operations#363]
* **Local Data Dictionary Name:**
 Psyche Mission Dictionary

* **Namespace ID Requested:**
 psyche

* **Discipline or Mission LDD?** 
 Mission

* **Steward Organization Name:** 
 PDS SBN-PSI

* **LDD Steward Name:** 
 Carol Neese

* **LDD Steward Email:** 
 neese@psi.edu

* **LDD Stewardship Team Members:** 

Ernest Cisneros ecisneros@asu.edu (aka spacerockjock)

* **LDD Description:**

The Psyche mission dictionary (psyche) contains classes, attributes, and rules specific to the Psyche mission and its instruments.

* **Rationale for creation of new LDD:**
 To support mission-specific metadata for the Psyche mission.

---

**Engineering Details**
- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If discipline LDD
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines

**Comment by c-suh** [comment]
@neese and @spacerockjock, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-psyche! Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
