### ISSUE TITLE
B13.1 Deploy and Release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#364]
By EOD Thursday 6/1
- https://github.com/NASA-PDS/software-issues-repo/issues/46 @tloubrieu-jpl 

On Monday 6/5
- https://github.com/NASA-PDS/operations/issues/372 @c-suh 
- https://github.com/NASA-PDS/operations/issues/368 @c-suh 
  - https://github.com/NASA-PDS/portal-tasks/issues/59 @c-suh 
- https://github.com/NASA-PDS/portal-tasks/issues/74 @c-suh 

Week of 6/5
- https://github.com/NASA-PDS/operations/issues/366 @c-suh 
  - https://github.com/NASA-PDS/doi-service/issues/399 @c-suh @alexdunnjpl 
- https://github.com/NASA-PDS/portal-tasks/issues/74 @c-suh
- https://github.com/NASA-PDS/operations/issues/367 @sjoshi-jpl @jimmie

By EOD Friday 6/9
- Announce Release - https://github.com/NASA-PDS/operations/issues/402 @jordanpadams

**Comment by jordanpadams** [comment]
@c-suh added new ticket to make sure we don't forget to actually launch the website.

https://github.com/NASA-PDS/portal-tasks/issues/74

Go for launch!

**Comment by c-suh** [comment]
@jordanpadams other than DOI Editor from https://github.com/NASA-PDS/operations/issues/366 (ongoing discussion via Slack), launch successful!

**Comment by c-suh** [comment]
@jordanpadams let me know when it's time to do the [post-release updates](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PostReleaseUpdates) (namely updating the LDD actions).

**Comment by nutjob4life** [comment]
Need to check in with @tloubrieu-jpl, or discuss at breakout 2023-07-18.

**Comment by c-suh** [comment]
As part of [#366](https://github.com/NASA-PDS/operations/issues/366) (already closed), the DOI Editor on production is now good and Ron has been notified. [Operations#367](https://github.com/NASA-PDS/operations/issues/367) is still open.

**Comment by nutjob4life** [comment]
"Smoke" test

**Comment by jordanpadams** [comment]
All sub-tasks complete. Done.
