### ISSUE TITLE
Prep and Stage dLDDs for Integration and Test

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#365]
## 💡 Description

**Planned for week of 4/10.**

### Prerequisites
* #370 
* https://github.com/NASA-PDS/pds4-information-model/issues/513

### Tasks
- [x] Prep - https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PrepdLDDsforStewardReview
- [x] Notify - @jordanpadams / @viviant100 send email to dLDD Stewards that their repos have new PRs for review

**Comment by c-suh** [comment]
@jordanpadams and @viviant100 - the discipline LDDs at https://github.com/pds-data-dictionaries/ have had pull requests created for IM v1.20.0.0 (1K00).

A note that the [Wave LDD](https://github.com/pds-data-dictionaries/ldd-wave/pulls) is included in this even though it is an in-development LDD. It is excluded when we [stage the LDD releases](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-StageLDDRelease) but not for this step of [prepping](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PrepdLDDsforStewardReview) them. Would you like me to adjust the prep script to do this?

**Comment by jordanpadams** [comment]
@c-suh we are a go for launch when you have the time! 🚀

**Comment by c-suh** [comment]
Updated the script to exclude the Wave LDD (tested locally). Ran the script (not locally) but the builds are failing.

**Comment by jordanpadams** [comment]
@jordanpadams completed today
