### ISSUE TITLE
B13.1 Deploy command-line tools and manual service deployments on EC2

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#366]
## 💡 Description

[See here for release to be used](https://nasa-pds.github.io/releases/13.1/index.html)

### Staging
 - [x] Validate [v3.2.0](https://github.com/NASA-PDS/validate/releases/tag/v3.2.0)
 - [x] Harvest [v3.7.6](https://github.com/NASA-PDS/harvest/releases/tag/v3.7.6)
 - [x] Registry Manager [v4.5.5](https://github.com/NASA-PDS/registry-mgr/releases/download/v4.5.5/registry-manager-4.5.5-bin.tar.gz)
 - [x] DOI Service [v2.3.6](https://github.com/NASA-PDS/doi-service/releases/tag/v2.3.6)
 - [x] DOI UI [v1.2.0](https://github.com/NASA-PDS/doi-ui/releases/tag/v1.2.0)

### Operations
 - [x] Validate [v3.2.0](https://github.com/NASA-PDS/validate/releases/tag/v3.2.0)
 - [x] Harvest [v3.7.6](https://github.com/NASA-PDS/harvest/releases/tag/v3.7.6)
 - [x] Registry Manager [v4.5.5](https://github.com/NASA-PDS/registry-mgr/releases/download/v4.5.5/registry-manager-4.5.5-bin.tar.gz)
 - [x] DOI Service [v2.3.6](https://github.com/NASA-PDS/doi-service/releases/tag/v2.3.6)
 - [x] DOI UI [v1.2.0](https://github.com/NASA-PDS/doi-ui/releases/tag/v1.2.0)
 - [x] New DOI Service Cron Jobs - https://github.com/NASA-PDS/doi-service/issues/399

**Comment by c-suh** [comment]
Am finding issues with DOI Editor. Discussion via Slack.

**Comment by tloubrieu-jpl** [comment]
Hi @c-suh , any feedback from the SA's (I am not able to see the ticket). If not can you ping them again for that ? Thanks

**Comment by c-suh** [comment]
Hi @tloubrieu-jpl I think our conversation petered out over Slack, and I hadn't got to asking the SAs about the new issue. I will do so now and update this comment with a link to that. (Sorry - forgot to update my last comment from 2 weeks ago. That ticket has been closed, but I just shared it with you so you can see the content.)
