### ISSUE TITLE
Deploy AWS services and scheduler tasks to AWS environment

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#367]
### Staging
 - ~Registry~
    - ~schema updates?~
    - ~reindex?~
 - [x] Registry API @tloubrieu-jpl 
   - [x] Smoke tests @miguelp1986 
 - [x] Monitoring
   - [x] Smoke tests @sjoshi-jpl @jimmie 

### Production
 - ~Registry~
 - [x] Registry API (terraform) @sjoshi-jpl @jimmie
     - [x] Smoke tests @miguelp1986 
 - [x] Monitoring
    - [x] Smoke tests @sjoshi-jpl @jimmie 

### NGAP
 - [x] Nucleus (terraform) @sjoshi-jpl @ramesh-maddegoda 
      - [x] Smoke tests @viviant100 @ramesh-maddegoda (and document smoke test)
 - [x] Monitoring
      - [x] Smoke tests @sjoshi-jpl @jimmie

**Comment by sjoshi-jpl** [comment]
@tloubrieu-jpl I've updated the steps to deploy registry-api based on the learnings last week.

https://wiki.jpl.nasa.gov/display/PDSEN/Deploy+Registry+API

**Comment by tloubrieu-jpl** [comment]
The workflow work with a workaround for OIDC authentication.

**Comment by tloubrieu-jpl** [comment]
@miguelp1986 @viviant100 I believe we are only mssing the smoke test to be run on the new deployment before we can close this ticket. Could you look at that ? Thanks

**Comment by sjoshi-jpl** [comment]
@tloubrieu-jpl the new updated terraform workflow is completed - https://github.com/NASA-PDS/nucleus/compare/main...terraform-deploy

Should I go ahead and create a PR?

**Comment by nutjob4life** [comment]
Smoke test: in progress. PRs all closed. End of sprint is 2023-07-20!

**Comment by nutjob4life** [comment]
Merged!

**Comment by jordanpadams** [comment]
@miguelp1986 @sjoshi-jpl @ramesh-maddegoda are we good with baseline deployment per B13.1? This does not include any of the new work being done with regard to monitoring and CD, as that is tracked separately.

**Comment by miguelp1986** [comment]
@jordanpadams I've smoke tested Production. Could you please share the endpoint for Registry API on staging? I can't seem to find it.

**Comment by viviant100** [comment]
https://pds.nasa.gov/api/search-en-gamma/1/swagger-ui/index.html

**Comment by jordanpadams** [comment]
Thanks @viviant100 . Do we know if there is a reason that is not at https://pds-gamma.jpl.nasa.gov/api/search/1/swagger-ui/index.html ? Everything else we do on gamma is represented this way except the Registry API? Maybe @tloubrieu-jpl can help us here

**Comment by ramesh-maddegoda** [comment]
> @miguelp1986 @sjoshi-jpl @ramesh-maddegoda are we good with baseline deployment per B13.1? This does not include any of the new work being done with regard to monitoring and CD, as that is tracked separately.

@jordanpadams , do you mean the baseline deployment of Nucleus? If so, we are good with the baseline deployment of Nucleus, as long as the Airflow environment does not have issues on AWS (such as the recent MWAA issues on NGAP).

**Comment by jordanpadams** [comment]
Calling this task completed for this build, but we will most likely need to improve this over time, especially Nucleus smoke tests.
