### ISSUE TITLE
B13.1 Finalize and Stage dLDDs for Release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#372]
## 💡 Description

- [x] Notify - notify dLDD Stewards one last 1 week warning to review their dLDDs and merge PRs (ping individual stewards as needed)
- [x] Stage - https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-StageLDDRelease

**Comment by c-suh** [comment]
Note: have checked through dLDD repos and most have closed pull requests for this build version. Exceptions are CTLI and Radar (and Wave, which is in-development), which do not have schema files for 1.20.0.0 in their build/development directories.

**Comment by c-suh** [comment]
Other notes:
- fixed code for converting pds4 version to alpha
- reran [workflow](https://github.com/pds-data-dictionaries/ldd-msn/actions/runs/4993948032) to release and tag LDD release for ldd-msn

**Comment by c-suh** [comment]
LDDs for 1.20.0.0/1K00 are on the gamma environment. Am emailing Steve the IngestLDD xml files for his final generation of all WebHelp files.

**Comment by c-suh** [comment]
@jordanpadams in talking with Steve, he noted that it's odd that only CTLI would not have an updated data dictionary for this build release. The [CTLI repo](https://github.com/pds-data-dictionaries/ldd-ctli) doesn't have a 1.20.0.0 in its `build/*` directories, but there is an [open PR](https://github.com/pds-data-dictionaries/ldd-ctli/pull/20) for 1.20.0.0. Please advise.
