### ISSUE TITLE
[lid-request] urn:nasa:pds:clps_to_2ab_nirvss_aim, urn:nasa:pds:clps_to_2ab_nirvss_lcs, urn:nasa:pds:clps_to_2ab_nirvss_spc

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#376]
* **PDS4 LID:** 
urn:nasa:pds:clps_to_2ab_nirvss_aim
urn:nasa:pds:clps_to_2ab_nirvss_lcs
urn:nasa:pds:clps_to_2ab_nirvss_spc

These are to replace urn:nasa:pds:clps_to_2ab_nirvss. Can this one be deprecated?

* **LID Type:** 
Bundle
  
* **Mission:** 
CLPS TO_2AB

* **Responsible Node:**
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Thanks, Jenn, those 3 were added, and the 1 deprecated
