### ISSUE TITLE
[ldd-release] ldd-proc LDD Version: 1.3.0.0 IM Version: 1.19.0.0

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#387]
* **Is the LDD IngestLDD in Github?** Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes

* **Need-by date**: 2023-04-20

* **Need-by date rationale**: N/A

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**: https://github.com/pds-data-dictionaries/ldd-proc/releases/tag/1J00_1300

* **PDS4 IM version to release with**: 1.19.0.0

**Comment by c-suh** [comment]
This LDD has been validated (with v3.2.0) and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#proc.
