### ISSUE TITLE
Submit new URS request

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#399]
## 💡 Description

After all other sub-tasks completed for https://github.com/nasa-pds/operations/issues/379, submit URS request. Reference previous URS304838.

**Comment by jordanpadams** [comment]
URS request submitted: URS316834. awaiting review and approval

**Comment by jordanpadams** [comment]
508 issues identified. new ticket now blocking this completion: https://github.com/NASA-PDS/operations/issues/412

**Comment by nutjob4life** [comment]
Awaiting

**Comment by jordanpadams** [comment]
URS approved.
