### ISSUE TITLE
Test and verify 508 compliance tool

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#412]
## 💡 Description

 - [ ] Test the ANDI tool [documented here](https://www.dhs.gov/news/2018/07/13/trusted-tester-v5-testing-tools) against pds-engineering-wp.jpl.nasa.gov
 - [ ] Verify report is something close to this report: [PDS Engineering report.docx](https://github.com/NASA-PDS/operations/files/11983331/PDS.Engineering.report.docx)
 - [ ] Document on wiki for portal updates that we always need to run this tool (or should we run it regularly?)

**Comment by tloubrieu-jpl** [comment]
linked to NASA-PDS/portal-tasks#77

**Comment by c-suh** [comment]
The website passed 508 compliance and has been switched over, rendering this unnecessary.
