### ISSUE TITLE
Monthly Metrics are not generating for EN the (1) tool metrics or (2) other reports

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#413]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When Colleen ran the process for the monthly metrics, the tool metrics and reports for EN are not generating.

### 🕵️ Expected behavior

Colleen expected metrics for EN.

### 📜 To Reproduce

```bash
1. Follow internal documentation for (1) tool metrics and (2) other reports
```

### 🩺 Test Data / Additional context

This GitHub ticket is belatedly created because it's taking more time than anticipated. Existing SA ticket: https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-4134.

### 🦄 Related requirements

🦄 #xyz

**Comment by nutjob4life** [comment]
Created today and linked with SAs; hope this last request will "fix it", then can tell Colleen and close it out!

**Comment by c-suh** [comment]
SAs delivered missing logs and ran tools for both metrics and reports for both May and June. Delivered these to Colleen just in time for her to get started on next month's metrics.

**Comment by viviant100** [comment]
skip I&T - machine issue, SA team is looking into this.
