### ISSUE TITLE
[ldd-request] Create new LDD "mgn"

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#414]
### Local Data Dictionary Name

Magellan

### LDD Short Name Identifier Requested

mgn

### Discipline or Mission Local Data Dictionary?

Mission

### LDD Steward Organization

PDS Geosciences Node

### LDD Steward Name

Jennifer Ward

### LDD Steward Email

jgward@wustl.edu

### LDD Steward Team Members

jennifergward, edguinness, dvpolitte

### LDD Description

The Magellan Mission Dictionary (mgn) contains classes, attributes and rules specific to the Magellan mission and its instruments.

### Rationale for creation of new LDD

Forthcoming PDS4 migrations and individual data provider submissions.

### ⚙️ Engineering Details

- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If Discipline LDD
  - [ ] add Steward to pdsddstewards@jpl.nasa.gov email list if they are not already on the list
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines
  - [ ] work with @jordanpadams to ping DD Stewards to establish CCB

**Comment by c-suh** [comment]
@jennifergward, @edguinness, and @dvpolitte, your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-mgn! Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
