### ISSUE TITLE
[lid-request] urn:nasa:pds:lra

### ISSUE THREAD

**Issue by mnhughes** [NASA-PDS/operations#416]
* **PDS4 LID:** urn:nasa:pds:lra

These LIDs need to be deprecated: 
urn:nasa:pds:clps_to_19c_lra, urn:nasa:pds:clps_to_2ab_lra, urn:nasa:pds:clps_to_2im_lra

* **LID Type:** Bundle
  
* **Mission:** multiple
* **Responsible Node:** GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by mnhughes** [comment]
Was the new LID reserved as well? I don’t see it when searching all PDS4 bundle LIDs

**Comment by rchenatjpl** [comment]
shoot, I didn't notice that part. Sorry. I just added it.
LRA is Laser Retroreflector Array? More importantly, there's only 1 bundle for the mission, or 1 bundle that is more important than any others?

**Comment by mnhughes** [comment]
Thanks. Yes, it is. They have decided to have just one bundle for the lra data from all clps missions that carry the instrument since it is a passive instrument and it would make more sense for the end user to organize it that way. The instrument may also be on some non-CLPS missions as well.
