### ISSUE TITLE
[ldd-release] IMG_SURFACE LDD Version: 1280 IM Version: 1G00

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#417]
* **Is the LDD IngestLDD in Github?** Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes

* **Need-by date**: ASAP

* **Need-by date rationale**: M2020 release

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**: https://github.com/pds-data-dictionaries/ldd-img_surface/releases/tag/1G00_1280

* **PDS4 IM version to release with**:

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _Name of LDD Ready for release_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool

**Comment by jordanpadams** [comment]
@c-suh sorry for the pivot, but can we get this LDD published stat?

**Comment by c-suh** [comment]
@jordanpadams this LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#img_surface.

**Comment by jordanpadams** [comment]
Thanks @c-suh !!!
