### ISSUE TITLE
[lid-request] urn:nasa:pds:clementine_lwir_bt

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS/operations#419]
* **PDS4 LID:** _proposed LID or LIDs_
* urn:nasa:pds:clementine_lwir_bt

* **LID Type:** _e.g. Bundle, Context_
* Bundle
  
* **Mission:** _if applicable_
* Clementine

* **Responsible Node:** _responsible node_
* Geosciences

---
Richard, We are starting to work on migration of the derived Clementine brightness temperature dataset. These data were derived from the Clementine LWIR (long-wavelength infrared) camera. I am open to other suggestions for the bundle LID. Let me know. Also, I notice that Imaging has migrated the Clementine raw image data, but there is no registered LID for that bundle.
Thanks,
Ed

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Approved. Thanks, Ed
