### ISSUE TITLE
hand off NSSDCA task to Colleen

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#420]
## 💡 Description
Have an initial, detailed walk-through of the procedure. Subsequent questions can be settled during the weekly tag-up.

**Comment by c-suh** [comment]
Have confirmed her GitHub account and gone over how to review the validation reports. She will work with the SAs to get access to the cloud machines again, and we will continue next week.

**Comment by jordanpadams** [comment]
closing as wontfix
