### ISSUE TITLE
[ldd-request] Create new LDD "vco"

### ISSUE THREAD

**Issue by murashinln** [NASA-PDS/operations#426]
### Local Data Dictionary Name

The Venus Climate Orbiter Akatsuki Mission Local Data Dictionary

### LDD Short Name Identifier Requested

vco

### Discipline or Mission Local Data Dictionary?

Mission

### LDD Steward Organization

JAXA

### LDD Steward Name

Shin-ya Murakami

### LDD Steward Email

murakami.shinya@jaxa.jp

### LDD Steward Team Members

murashinln

### LDD Description

 The Venus Climate Orbiter Akatsuki Mission Local Data Dictionary contains classes, attributes and rules specific to the Venus Climate Orbiter Akatsuki Mission and its instruments.

### Rationale for creation of new LDD

 This LDD is needed to describe the specifics of both the Venus Climate Orbiter Akatsuki Mission and the instrumentation on board the Akatsuki spacecraft.

### ⚙️ Engineering Details

- [x] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If Discipline LDD
  - [ ] add Steward to pdsddstewards@jpl.nasa.gov email list if they are not already on the list
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines
  - [ ] work with @jordanpadams to ping DD Stewards to establish CCB

**Comment by murashinln** [comment]
Jordan suggested via email to mention a bug on the hyb2 entry in [the PDS4 namespace registry PDF](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf) . `XML Schema Namespace` for `hyb2` is `http://darts.isas.jaxa.jp/pds4/` but it should be `http://darts.isas.jaxa.jp/pds4/mission/hyb2/v1`.

**Comment by c-suh** [comment]
@jordanpadams pardon the ticket above and let me know if I should reopen it for Steve to add "vco" to the namespace registry. Thank you.

**Comment by jordanpadams** [comment]
@jshughes can you help update the namespace registry per above?

**Comment by c-suh** [comment]
@murashinln your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-vco! Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
