### ISSUE TITLE
Deploy and Test legacy registry components on OL8

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/operations#431]
## 💡 Description

Clean-up:
- [x] search-core
- [x] search-service
- [x] storage-service
- [x] product-service
- [x] harvest-pds3
- [x] harvest-pds4
- [x] catalog
- [x] ds-view
- [x] search-ui

Deploy latest:
- [x] registry-harvest-legacy
- [x] registry-pds3-catalog
- [x] registry-mgr-legacy
- [x] ds-view
- [x] search-ui

Requires to switch the java version used to 8 and remove the log4j vulnerability on legacy harvest

**Comment by c-suh** [comment]
@jordanpadams is this ticket an overlap with https://github.com/NASA-PDS/registry-mgr-legacy/issues/20, or should that ticket be changed to locally only and not on gamma? Either way, your last comment is about a Docker issue on the gamma EC2. If that hasn't been resolved, would you mind sharing the DSIO ticket with me so that I can be aware of its status?

**Comment by jordanpadams** [comment]
@c-suh yes tightly coupled. did not realize this ticket already existed. close whichever you want

**Comment by c-suh** [comment]
Copying Jordan's aforementioned comment from the other ticket (with an edited title and now closed):

> once we get the DSIO ticket resolved with docker on the gamma EC2, we can jump over there and test

**Comment by c-suh** [comment]
Waiting on latest releases to deploy and on the aforementioned Docker issue.

**Comment by tloubrieu-jpl** [comment]
Deployment is done, test remains to be done.

**Comment by c-suh** [comment]
After much ado, the SAs have Docker up and running! I have loaded both PDS3 and PDS4 data, have requested the SAs to enable SSL for Solr, and am updating documentation in the meantime.

**Comment by jordanpadams** [comment]
Status: Reviewed with Ops team, @jordanpadams to take a look.

**Comment by jordanpadams** [comment]
We will call this done for now. See https://github.com/NASA-PDS/registry-mgr-legacy/issues/20 for getting the remaining legacy registry components tested and deployed.
