### ISSUE TITLE
[ldd-release] ldd-mro LDD Version:1.2.2.0 IM Version: 1.K.0.0, 1.J.0.0, 1.I.0.0

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#436]
* **Is the LDD IngestLDD in Github?** Yes

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** Yes

* **Need-by date**: No huge rush

* **Need-by date rationale**: n/a

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**: https://github.com/pds-data-dictionaries/ldd-mro/releases

* **PDS4 IM version to release with**: 1.K.0.0 (but I guess it would be nice for I and J

**Comment by jordanpadams** [comment]
@thareUSGS we got your request. we are swamped with some other stuff in operations, but will get back to you

**Comment by dvpolitte** [comment]
Is there an ETA for this issue to be closed? At GEO, we've got a bundle of MRO-derived data that uses this version of the dictionary. We're aiming to release it this week, and I understand that we won't be able to ingest the bundle into the registry until the dictionary is released. Thanks!

**Comment by jordanpadams** [comment]
@dvpolitte sorry. lots of things getting juggled right now. we will put this at the top of our list.

**Comment by jordanpadams** [comment]
@c-suh in between the pds-gamma-ol8 testing, can we get this released?

**Comment by c-suh** [comment]
@jordanpadams and @dvpolitte the LDDs have been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#mro!

**Comment by jordanpadams** [comment]
thanks @c-suh !
