### ISSUE TITLE
[nssdca-delivery] PDS_ATM Pack13 (PHOENIX)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#448]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[pdsatm_pack13_20231018.tar.gz](https://github.com/NASA-PDS/operations/files/13029585/pdsatm_pack13_20231018.tar.gz)

* **Validation report**: 
[pdsatm_pack13_validationreports.tar.gz](https://github.com/NASA-PDS/operations/files/13029581/pdsatm_pack13_validationreports.tar.gz)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by oddes** [comment]
@tinagueth : These 5 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:phx_ao_v2.0_20231018
urn:nasa:pds:system_bundle:product_sip_deep_archive:phx_ase_v2.0_20231018
urn:nasa:pds:system_bundle:product_sip_deep_archive:phx_lidar_v2.0_20231018
urn:nasa:pds:system_bundle:product_sip_deep_archive:phx_met_v2.0_20231018
urn:nasa:pds:system_bundle:product_sip_deep_archive:phx_tt_v2.0_20231018

**Comment by tinagueth** [comment]
All SIP/AIP for these bundles have been archived
