### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:co_iss_global-maps (resubmission)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#464]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[co_iss_global-maps_20231117.tar.gz](https://github.com/NASA-PDS/operations/files/13394912/co_iss_global-maps_20231117.tar.gz)

* **Validation report**: 
[coiss_globalmapsv1.txt](https://github.com/NASA-PDS/operations/files/13394899/coiss_globalmapsv1.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by smclaughlin7** [comment]
@tinagueth Thank you for correcting those two products in #462 and remaking/resubmitting a new delivery package for the "co_iss_global-maps" bundle!

**Comment by tinagueth** [comment]
@smclaughlin7 Thankfully, Lyle was quick to respond to this, and fingers crossed it all goes well. :)

**Comment by oddes** [comment]
@tinagueth  This set has been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231117

**Comment by tinagueth** [comment]
there were some minor schemas/schematrons pathway changes made to this bundle the other day. I will have to resubmit this bundle to account for these changes. Sorry about this. See new Issue #471

**Comment by jordanpadams** [comment]
Closing for #471

@smclaughlin7 can we remove or delete this submission? `urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231117`

**Comment by smclaughlin7** [comment]
@jordanpadams We should keep this submission #464 SIP `urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231117`. It has already been sent to Ingest and is being processed.  When we receive the revised bundle via submission #471 `urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231213`, we'll just go ahead and ingest that newer iteration as usual.  Fortunately the bundle is small, < ~2 GB and ~70 products.  :-)
