### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:magellan_gxdr::1.0

### ISSUE THREAD

**Issue by gbowen99** [NASA-PDS/operations#468]
### Discipline Node Information

* **Delivering Node**: _please enter your DN here for record keeping purposes_ 
* Geosciences Node

* **NSSDCA Delivery Package**: _please upload the files output by PDS Deep Archive as a TAR.GZ or ZIP file here, or supply a URL to download from_
* 
[Archive.zip](https://github.com/NASA-PDS/operations/files/14224764/Archive.zip)

* **Validation report**: _please upload a TXT report or screenshot of PDS4 Validate Tool run on your bundle. NSSDCA only accepts valid PDS4 bundles. be sure you run validate with the `-R pds4.bundle` flag enabled to ensure all integrity checks are completed successfully._
* 
[mgn_gxdr_report.txt](https://github.com/NASA-PDS/operations/files/13532254/mgn_gxdr_report.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by smclaughlin7** [comment]
@gbowen99
The URLs in the SIP manifest file "magellan_gxdr_v1.0_20231201_sip_v1.0.tab" are malformed, e.g.
`//isilon-pri-data/pds-san/data/mgn/urn-nasa-pds-magellan_gxdr/bundle_mgn_gxdr.xml`. Please check with EN / @oddes, but you should be able to force the Deep Archive tool to form full URLs in the manifest, e.g., 
`https://pds-geosciences.wustl.edu/mgn/urn-nasa-pds-magellan_gxdr/bundle_mgn_gxdr.xml`.

@oddes
Can @gbowen99 upload the updated, replacement Deep Archive package (with corrected URLs in the manifest) to this ticket?

**Comment by oddes** [comment]
@smclaughlin7 Please go ahead and update.

**Comment by smclaughlin7** [comment]
> Please go ahead and update.

@oddes Just to clarify, @gbowen99 should make a new Deep Archive package and post it here (#468).

**Comment by gbowen99** [comment]
Here is the updated delivery package with a corrected SIP manifest file:
[urn-nasa-pds-magellan_gxdr--1.0.zip](https://github.com/NASA-PDS/operations/files/13665747/urn-nasa-pds-magellan_gxdr--1.0.zip)
And here is the updated validation report with content validation enabled: 
[mgn_gxdr_validation_report.txt](https://github.com/NASA-PDS/operations/files/13665749/mgn_gxdr_validation_report.txt)

Let me know if there is anything else either of you need.

-Gary

**Comment by smclaughlin7** [comment]
@gbowen99 Thank you for posting the updated delivery package with a corrected SIP manifest file for @oddes!

**Comment by c-suh** [comment]
Hello @gbowen99! Thank you very much for the updated delivery package and my apologies for the delay. In validating the delivery package linked in [your most recent comment](https://github.com/NASA-PDS/operations/issues/468#issuecomment-1854708244), there are 2 different errors flagged multiple times. I am attaching the report below for your perusal; please address these then attach the twice updated delivery package and report like you did above. Thank you!

-Catherine

---
**Validation report:** [magellan_gxdr_v1.0_20231213-validate.txt](https://github.com/NASA-PDS/operations/files/14070119/magellan_gxdr_v1.0_20231213-validate.txt)

**Comment by c-suh** [comment]
Node's re-delivery of packages is currently blocked by [this deep-archive bug](https://github.com/NASA-PDS/deep-archive/issues/155).

**Comment by jordanpadams** [comment]
@c-suh I have attached an updated set of products above.

@gbowen99 we are in the process of fixing a couple bugs. Once those are complete, we will let you know so you can upgrade your tools and start submitting more packages.

**Comment by gbowen99** [comment]
@jordanpadams thank you for the update!

**Comment by gbowen99** [comment]
I accidentally clicked "Close with comment" on my last comment. Please ignore that.

**Comment by c-suh** [comment]
@gbowen99 the package which Jordan attached has been posted for NSSDCA processing! (The deep archive bug is still being addressed.) From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:magellan_gxdr_v1.0_20240208

**Comment by c-suh** [comment]
@jordanpadams this package, magellan_gxdr_v1.0, has been posted for NSSDCA.

**Comment by c-suh** [comment]
This package has been Submitted to Ingest:
- urn:nasa:pds:system_bundle:product_sip_deep_archive:magellan_gxdr_v1.0_20240208

**Comment by c-suh** [comment]
Same status.

**Comment by c-suh** [comment]
@gbowen99 this package has been validated by NSSDCA, submitted to Ingest, and Ingested. NSSDCA has now taken responsibility.
