### ISSUE TITLE
[nssdca-delivery]  bc_spice, dart.spice, em16_spice, insight.spice, mars2020.spice, maven.spice, orex.spice, vco_spice

### ISSUE THREAD

**Issue by alyssambailey** [NASA-PDS/operations#470]
### Discipline Node Information

* **Delivering Node**: NAIF

      This delivery consists of a total of 20 SPICE Bundle products
      for BepiColumbo, DART,  ExoMars2016, Insight, Mars2020, MAVEN, OSIRIS-REx, and VCO.

* **NSSDCA Delivery Package**:  https://naif.jpl.nasa.gov/pub/naif/pds/misc/nssdca/pds4/202312/
      Additionally, I have provided this tar.gz for your convenience - 
[nssdca_pds4_bc_dart_em16_insight_mars2020_maven_orex_vco_202312_naif.tar.gz](https://github.com/NASA-PDS/operations/files/13574108/nssdca_pds4_bc_dart_em16_insight_mars2020_maven_orex_vco_202312_naif.tar.gz)

* **Validation report**: Validate version 3.1.1 - 
[validation_reports_naif_2023.tar.gz](https://github.com/NASA-PDS/operations/files/13574110/validation_reports_naif_2023.tar.gz)

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by jordanpadams** [comment]
@alyssambailey just as a heads up, it looks like there are some table definition and file size errors identified in the VCO and Maven releases. Are those expected?

**Comment by jordanpadams** [comment]
thanks @alyssambailey! in the future, when submitting the validation reports, if you could provide rationale for any known validation errors that would be great! It will just help our Operations team understand why they are seeing some errors being thrown from validate and not ping you about them again.

additionally, it looks like you are running a somewhat older version of validate (3.1.1). The latest greatest version is [online here](https://github.com/NASA-PDS/validate/releases/latest) if you want to upgrade when you have a chance.

**Comment by c-suh** [comment]
@alyssambailey the single tarball of all the files is very much appreciated (as are the explanations of the errors)! These 20 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:bc_spice_v1.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:bc_spice_v2.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:bc_spice_v3.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v1.0_20231205
urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v2.0_20231205
urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v3.0_20231205
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v7.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v8.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v9.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v15.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v16.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v6.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v7.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v8.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v32.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v33.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v34.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v35.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v13.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:vco_spice_v2.0_20231128

@smclaughlin7 :point_up: :slightly_smiling_face:

**Comment by c-suh** [comment]
The following 20 packages have been Submitted to Ingest:
urn:nasa:pds:system_bundle:product_sip_deep_archive:bc_spice_v1.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:bc_spice_v2.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:bc_spice_v3.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v1.0_20231205
urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v2.0_20231205
urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v3.0_20231205
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v7.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v8.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:em16_spice_v9.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v15.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:insight.spice_v16.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v6.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v7.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:mars2020.spice_v8.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v32.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v33.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v34.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:maven.spice_v35.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:orex.spice_v13.0_20231128
urn:nasa:pds:system_bundle:product_sip_deep_archive:vco_spice_v2.0_20231128

**Comment by c-suh** [comment]
Status is the same for the 20 packages.

**Comment by c-suh** [comment]
Status is the same for all 20 packages.

**Comment by c-suh** [comment]
@alyssambailey, 19 of 20 of these packages have been validated by NSSDCA, submitted to Ingest, and Ingested. NSSDCA has now taken responsibility or these 19 packages. The last package, urn:nasa:pds:system_bundle:product_sip_deep_archive:dart.spice_v3.0_20231205, has been submitted to ingest.

**Comment by c-suh** [comment]
@alyssambailey the last package has been archived by NSSDCA.
