### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:co_iss_global-maps (2nd resubmission)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#471]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[co_iss_global-maps_20231213.tar.gz](https://github.com/NASA-PDS/operations/files/13662867/co_iss_global-maps_20231213.tar.gz)

* **Validation report**: 
[coiss_globalmapsv1.txt](https://github.com/NASA-PDS/operations/files/13662870/coiss_globalmapsv1.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth and @smclaughlin7 this set has been posted for NSSDCA processing! From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231213

**Comment by c-suh** [comment]
The following package has been Submitted to Ingest:
urn:nasa:pds:system_bundle:product_sip_deep_archive:co_iss_global-maps_v1.0_20231213

**Comment by c-suh** [comment]
Status is the same.

**Comment by c-suh** [comment]
Status is the same.

**Comment by c-suh** [comment]
@tinagueth, this package has been validated by NSSDCA, submitted to Ingest, and Ingested. NSSDCA has now taken responsibility.
