### ISSUE TITLE
[nssdca-delivery] Viking Orbiter Pack (resubmission)

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#472]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[pdsatm_VikOrb_20231213.tar.gz](https://github.com/NASA-PDS/operations/files/13664678/pdsatm_VikOrb_20231213.tar.gz)

* **Validation report**: 
[pdsatm_VikOrb_validationreports.tar.gz](https://github.com/NASA-PDS/operations/files/13664676/pdsatm_VikOrb_validationreports.tar.gz)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth and @smclaughlin7 these 2 sets have been posted for NSSDCA processing! From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:vo_irtm_v1.0_20231213
urn:nasa:pds:system_bundle:product_sip_deep_archive:vo_mawd_v1.0_20231213

**Comment by c-suh** [comment]
The following 2 packages have been Submitted to Ingest:
urn:nasa:pds:system_bundle:product_sip_deep_archive:vo_irtm_v1.0_20231213
urn:nasa:pds:system_bundle:product_sip_deep_archive:vo_mawd_v1.0_20231213

**Comment by c-suh** [comment]
Status is the same for the 2 packages.

**Comment by c-suh** [comment]
Status is the same.

**Comment by c-suh** [comment]
Same status.

**Comment by c-suh** [comment]
@tinagueth both packages have been validated by NSSDCA, submitted to Ingest, and Ingested. NSSDCA has now taken responsibility.
