### ISSUE TITLE
[ldd-request] Create new LDD "kplo"

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#474]
### Local Data Dictionary Name

Korea Pathfinder Lunar Orbiter

### LDD Short Name Identifier Requested

kplo

### Discipline or Mission Local Data Dictionary?

Mission

### LDD Steward Organization

Cartography and Imaging Sciences Discipline Node

### LDD Steward Name

Trent Hare

### LDD Steward Email

thare@usgs.gov

### LDD Steward Team Members

thareUSGS

### LDD Description

The KPLO dictionary contains classes that describe aspects of the Korea Pathfinder Lunar Orbiter mission and related instruments.

### Rationale for creation of new LDD

NASA's ShadowCAM requires mission attributes for their labels.

### ⚙️ Engineering Details

- [ ] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] If Discipline LDD
  - [ ] add Steward to pdsddstewards@jpl.nasa.gov email list if they are not already on the list
  - [ ] update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)
  - [ ] create directory and index files for Git
  - [ ] create symlink on all machines
  - [ ] work with @jordanpadams to ping DD Stewards to establish CCB

**Comment by jordanpadams** [comment]
@thareUSGS your repo and namespace are good to go. @jshughes need to add this to the namespace registry, but otherwise we are good. https://github.com/pds-data-dictionaries/ldd-kplo

**Comment by thareUSGS** [comment]
I knew it would likely fail a build until all parts were added, but just wanted to get the working version out there. No huge rush.

**Comment by jshughes** [comment]
@thareUSGS @jordanpadams 

We are still missing the prefix for the XML Namespace.

The namespace identifier 'kplo' (Korea Pathfinder Lunar Orbiter) was added on 2021-08-18. The request was from Joo Hyeon Kim. Eunhyeuk Kim, eunhyeuk@kari.re.kr is contact. The LID prefix is currently urn:kari:kpds.
There was no XML namespace provided but I have the note "KPDS will be opened for web-service in early 2024".

The namespace identifier 'kpds' (KARI Planetary Data System) was also added on 2021-08-18. urn:kari:kpds - Joo Hyeon Kim (KPDS Manager) - kl0630@kari.re.kr. 

Given "urn:kari:kpds" as the LID prefix, I would expect something like http://...kari/kpds/v1 based on http://psa.esa.int/psa/v1

Or if this is a PDS DN submission, then something like http://pds.nasa.gov/pds4/mission/kplo/v1. However this would preclude the use of 'kplo' by the KPDS.

Please advise.

**Comment by jordanpadams** [comment]
@thareUSGS will KPDS be hosting these schemas/schematrons? Or will these be on pds.nasa.gov? Or TBD.

@jshughes any way we could add some flag to overwrite the default namespace?

**Comment by thareUSGS** [comment]
Jordan and Steve,
   I'm not sure I am up-to-date with what needs to happen.

>> KPDS be hosting these schemas/schematrons
Not sure, but we will need them locally for ShadowCAM. So can we offer to host them?

Steve - If I recall isn't there an issue with "KPDS" namespace or as a context product...?

Lastly, Boris actually did have some late comments. Mostly just place-holder NAIF IDs which might need to be updated. Not a huge priority but I will keep it on my to-do list.

-Trent

________________________________
From: Jordan Padams ***@***.***>
Sent: Thursday, December 28, 2023 4:15 PM
To: NASA-PDS/operations ***@***.***>
Cc: Hare, Trent M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-PDS/operations] [ldd-request] Create new LDD "kplo" (Issue #474)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



@thareUSGS<https://github.com/thareUSGS> will KPDS be hosting these schemas/schematrons? Or will these be on pds.nasa.gov? Or TBD.

@jshughes<https://github.com/jshughes> any way we could add some flag to overwrite the default namespace?

**Comment by jshughes** [comment]
> Steve - If I recall isn't there an issue with "KPDS" namespace or as a context product...?

Yes, the PDS4 schematron rule that validates all LID prefixes was updated to allow "urn:kari:kpds:".

The remaining issue is that we do not know the URL for the "KPDS".  If the KPDA is hosting the data, then http://pds.nasa.gov/pds4/pds/ will not work. For example, ESA PSA uses http://psa.esa.int/psa/v1.
