### ISSUE TITLE
Please release new mission dictionary LDD-NH as soon as convenient

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/operations#475]
* **Is the LDD IngestLDD in Github?** _Yes_

* **Has the LDD Namespace been registered in the [Namespace Registry](https://github.com/NASA-PDS/pds4-information-model/raw/main/docs/namespace-registry/pds-namespace-registry.pdf)?** _Yes_

* **Need-by date**:  2 January 2024
Note that the data have already been posted for public review, so it is important to make the dictionary information available as soon as possible, but not so important as to require disruption of planned vacations over the holidays.

* **Need-by date rationale**: The data have already been posted for public review to meet a January 1 deadline, so it is important to make the dictionary information available as soon as possible, but not so important as to require disruption of planned vacations over the holidays.

----

### Latest LDD is in Github

* **GitHub Tagged Release of LDD**: https://github.com/pds-data-dictionaries/ldd-nh/releases/tag/1L00_1000
* Please also include, on the  with IMs 1.20 and 1.19, the versions used in the published data:
* https://github.com/pds-data-dictionaries/ldd-nh/releases/tag/1K00_1000
* https://github.com/pds-data-dictionaries/ldd-nh/releases/tag/1J00_1000

* **PDS4 IM version to release with**: Not sure what this is asking. We need versions to support the current (1.21) IM as well as the previous two (1.20 and 1.19).

_NOTE: A code freeze is expected for this LDD repo as soon as this request is submitted in order to avoid collision with additional changes. Once this ticket has been closed, active development may resume. If the LDD to release is not in the repo, PDS Operations will upload those files to the repo._

### Latest LDD is NOT in Github

* **LDD**: _New Horizons Mission Dictionary_
* **LDD Submission Package (.zip)**: _zip consisting of the following files generated from LDDTool_
    * .xsd – XML Schema file
    * .sch – Schematron file
    * .xml – Label file
    * .JSON – JSON File
    * IngestLDD.xml - Ingest LDD File used as input to LDDTool
    
I don't understand what I'm supposed to do with this "submission package" section.

**Comment by acraugh** [comment]
Ah - now I see I was supposed to ignore it...

**Comment by jordanpadams** [comment]
@acraugh these have been posted. https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#nh
