### ISSUE TITLE
[lid-request] urn:nasa:pds:magellan_losapdr

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS/operations#482]
* **PDS4 LID:** _proposed LID or LIDs_
urn:nasa:pds:magellan_losapdr

* **LID Type:** _e.g. Bundle, Context_
 Bundle
 
* **Mission:** _if applicable_
Magellan

* **Responsible Node:** _responsible node_
Geosciences Node
---

Note: This is for migration of the Magellan Line of Sight Acceleration Profile Data Record (LOSAPDR) dataset.

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
done. Thanks, Ed
