### ISSUE TITLE
[nssdca-delivery] Huygens Probe Submission

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#486]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[pdsatm_HuygensProbe_20240208.tar.gz](https://github.com/NASA-PDS/operations/files/14213447/pdsatm_HuygensProbe_20240208.tar.gz)

* **Validation report**: 
[pdsatm_HuygensProbe_validationreports.tar.gz](https://github.com/NASA-PDS/operations/files/14213450/pdsatm_HuygensProbe_validationreports.tar.gz)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by tinagueth** [comment]
@c-suh I am adding this comment from Lyle to give you a heads up: "There is one PDF file in the hpdwe_bundle that fails for PDF/A-1b. All attempts to make it comply have failed so that’s just how it’s going to be."
Thanks, Tina

**Comment by c-suh** [comment]
@tinagueth I appreciate the heads up from Lyle! I have included the package, and these 8 sets have been posted for NSSDCA processing. From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_acp_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_disr_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_dtwg_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_dwe_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_gcms_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_hasi_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_hk_v1.0_20240208
urn:nasa:pds:system_bundle:product_sip_deep_archive:hp_ssp_v1.0_20240208

**Comment by c-suh** [comment]
All 8 packages have been Submitted to Ingest.

**Comment by c-suh** [comment]
Same status for all 8 packages.

**Comment by c-suh** [comment]
@tinagueth all 8 packages have been validated by NSSDCA, submitted to Ingest, and Ingested. NSSDCA has now taken responsibility.
