### ISSUE TITLE
[ldd-release]CTLI_1K00_2100 

### ISSUE THREAD

**Issue by lylehuber** [NASA-PDS/operations#487]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-ctli

**Comment by c-suh** [comment]
@lylehuber this LDD has been validated and posted at https://pds.nasa.gov/datastandards/dictionaries/index-1.20.0.0.shtml#ctli!
