### ISSUE TITLE
urn:nasa:pds:magellan_losapdr

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS/operations#488]
* **PDS4 LID:** _proposed LID or LIDs_
urn:nasa:pds:magellan_losapdr

* **LID Type:** _e.g. Bundle, Context_
Bundle
  
* **Mission:** _if applicable_
Magellan

* **Responsible Node:** _responsible node_
Geosciences Node
---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Thanks, Ed. This got updated.
