### ISSUE TITLE
[ldd-release] KPLO LDD Version:1.0.0.0 IM Version:1.21.0.0

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#492]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

First week of March. Sorry earlier the better for testing.

### Need by date rationale

Initial review going very well. Trying to release prior to LPSC (March 11, 2024). The Website for Missions will need KPLO added to the table: https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-kplo/releases

### PDS4 IM Versions to Release

1.21.0.0

**Comment by thareUSGS** [comment]
Did a quick new push just now, but still not sure how to deal with issue above. Speficially the places with "tbdmission":

    targetNamespace="http://tbdmission/kplo/v1"
    xmlns:kplo="http://tbdmission/kplo/v1"

**Comment by c-suh** [comment]
@thareUSGS apologies for the late response and thank you for the push! I will take a look at the "tbdmission" instances and have an update for you tomorrow.

**Comment by jordanpadams** [comment]
@thareUSGS we are working on this. standby.

**Comment by jordanpadams** [comment]
@thareUSGS @c-suh per https://github.com/pds-data-dictionaries/ldd-kplo/commit/d6a77101d65a6d9a100ae15b5190b48068caa483, I was able to manually generate the LDDs with a frankenstein version of LDDTool, but it all seems to check out now. Feel free to take a look at the new tagged release and let me know if there are any issues.

**Comment by thareUSGS** [comment]
If we are good with targetNamespace and xmlns:kplo -- I think this ready.  We can ask for the kari address to get a redirect from that team.

```
    targetNamespace="http://www.kari.re.kr/kpdsmission/kplo/v1"
    xmlns:kplo="http://www.kari.re.kr/kpdsmission/kplo/v1"
    xmlns:pds="http://pds.nasa.gov/pds4/pds/v1"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="1.0.0.0">
 
    <xs:import namespace="http://pds.nasa.gov/pds4/pds/v1" 
          schemaLocation="https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1L00.xsd"/>
```

**Comment by c-suh** [comment]
@thareUSGS this LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#kplo!

**Comment by thareUSGS** [comment]
@c-suh We don't need to reopen - but quick question. The ShadowCAM team just asked.  

are we sure it is:
http://www.kari.re.kr/kpdsmission/kplo/v1
and not:
http://www.kari.re.kr/kpds/mission/kplo/v1

I assumed the site simply wasn't yet available? I don't think we need a new version, but can bank it for the next minor release (unless others disagree).

**Comment by c-suh** [comment]
@thareUSGS great catch and apologies for not having caught it myself! @jordanpadams :point_up:

**Comment by jordanpadams** [comment]
@c-suh @thareUSGS I will close with the loop with Steve and make sure we have this right.

**Comment by jordanpadams** [comment]
@c-suh you can re-release this version: https://github.com/pds-data-dictionaries/ldd-kplo/releases/download/1L00_1000/PDS4_KPLO_1L00_1000.zip

**Comment by jordanpadams** [comment]
@c-suh new, better version now available here to replace what we put online originally: https://github.com/pds-data-dictionaries/ldd-kplo/releases/download/1L00_1000/PDS4_KPLO_1L00_1000.zip

@thareUSGS ☝️

**Comment by c-suh** [comment]
@thareUSGS the new version has been validated and posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#kplo!
