### ISSUE TITLE
[ldd-release] CLIPPER LDD Version: 1.0.0.0 IM Version: 1.19.0.0 - 1.21.0.0

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#493]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

n/a. As you can get to it.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-clipper/releases

### PDS4 IM Versions to Release

1.19.0.0 must
1.20.0.0, 1.21.0.0 if possible

**Comment by c-suh** [comment]
@thareUSGS these 3 LDDs have been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#clipper!
