### ISSUE TITLE
Update and Test Tool Registry and Data Dictionary Search for OL8

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/operations#496]
per https://github.com/NASA-PDS/operations/issues/395#issuecomment-2008053626

- [ ] Tool Registry (possible overlap with https://github.com/NASA-PDS/operations/issues/434)
- [ ] Data Dictionary Search

**Comment by jordanpadams** [comment]
@c-suh let's [deprecate dd-search tool](https://github.com/NASA-PDS/portal-tasks/issues/94) and let's put a note that the Tool Registry is down for the time being for now. This will require a bit of rework of the registry servlet per https://github.com/NASA-PDS/search-ui-legacy/issues/34

**Comment by c-suh** [comment]
Tool Registry is working and Data Dictionary Search has been replaced with links to the WebHelp generated documentation for all LDDs.
