### ISSUE TITLE
[ldd-release] Cassini_1J00_1700

### ISSUE THREAD

**Issue by lylehuber** [NASA-PDS/operations#500]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-cassini/releases/tag/1J00_1700

**Comment by c-suh** [comment]
Hi @lylehuber this LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#cassini (along with GEOM 1J00 1970 on the [1.19.0.0 page](https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#geom))!
