### ISSUE TITLE
[ldd-request] Create new LDD "VIPER"

### ISSUE THREAD

**Issue by mnhughes** [NASA-PDS/operations#504]
### Local Data Dictionary Name

Volatiles Investigating Polar Exploration Rover

### LDD Short Name Identifier Requested

viper

### Discipline or Mission Local Data Dictionary?

Mission

### LDD Steward Organization

PDS Geosciences Node

### LDD Steward Name

Madison Touran 

### LDD Steward Email

mnhughes@wustl.edu

### LDD Steward Team Members

mnhughes, jennifergward

### LDD Description

The VIPER mission dictionary contains classes and attributes specific to the VIPER mission and its instruments.

### Rationale for creation of new LDD

Archiving for new mission.

### ⚙️ Engineering Details

- [x] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [ ] ~If Discipline LDD~
  - [ ] ~add Steward to pdsddstewards@jpl.nasa.gov email list if they are not already on the list~
  - [ ] ~update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)~
  - [ ] ~create directory and index files for Git~
  - [ ] ~create symlink on all machines~
  - [ ] ~work with @jordanpadams to ping DD Stewards to establish CCB~

**Comment by jordanpadams** [comment]
All sub-tasks completed.
