### ISSUE TITLE
[lid-request] urn:nasa:pds:context:other_investigation:clps

### ISSUE THREAD

**Issue by alyssambailey** [NASA-PDS/operations#505]
* **PDS4 LID:** [_proposed LID or LIDs_](urn:nasa:pds:context:other_investigation:clps)

* **LID Type:** Context_
  
* **Mission:** CLPS

* **Responsible Node:** NAIF

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
Hi, @alyssambailey , I'm bringing in @mnhughes  here because CLPS confuses me. Your proposed LID
  urn:nasa:pds:context:other_investigation:clps
is to link all the various CLPS missions together? If so, Madison, is this something you guys have thought about and have a solution for? If not, help! Thanks

**Comment by alyssambailey** [comment]
Hi @rchenatjpl I have a draft context product xml for this where I connect the CLPS Initiative to the missions under it by their spacecraft using investigation_to_instrument_host
ex. 
        <Internal_Reference>
            <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.clps_to_2ab_pll</lid_reference>
            <reference_type>investigation_to_instrument_host</reference_type>
        </Internal_Reference>
I am getting a better description of the CLPS Initiative for this and will send you the draft once I have that. 
Is this approach okay?

**Comment by rchenatjpl** [comment]
Wait, I found email between Madison and me a year ago in which it seemed that GEO had ideas on what the context products for the spacecraft would be. Missions too?

If GEO has nothing in mind, I'm not sure which is better:
urn:nasa:pds:context:investigation:other_investigation.clps or
urn:nasa:pds:context:investigation:mission.clps
The guide to context products https://pds.nasa.gov/datastandards/documents/context/PDS4_Context_Products_Guide.v3.pdf says:
_Other Investigation_ products typically describe projects that have multiple investigators and/or
summarize multiple studies.
_Mission investigations_ allow different data and documentation to be tied to a mission.
Probably other_investigation. I dunno. I'll go with the groupthink.

**Comment by mnhughes** [comment]
Hi Richard, yes, I agree that other_investigation makes more sense in this case for CLPS.

**Comment by rchenatjpl** [comment]
Great. So @alyssambailey or @mnhughes, can either/both of you create a first draft of the context product for other_investigation.clps? Or I can take that shot, especially if you send me as complete a list of proposed LIDs of CLPS spacecraft as you have. Thanks

**Comment by alyssambailey** [comment]
[other_investigation.clps_1.0.xml.txt](https://github.com/NASA-PDS/operations/files/15000188/other_investigation.clps_1.0.xml.txt)

Here is a draft! I will have an update to the description once that gets sent to me.

**Comment by alyssambailey** [comment]
@rchenatjpl I am expecting an updated description for it by the end of this week and then I will send you an updated one.

**Comment by alyssambailey** [comment]
@rchenatjpl I have attached an updated file. I updated the description and the start date. I set the start date to be 1/8/2024 which was the launch date of clps_to_2ab, @mnhughes do you think that makes sense? 
[other_investigation.clps_1.1.xml.txt](https://github.com/NASA-PDS/operations/files/15194888/other_investigation.clps_1.1.xml.txt)

**Comment by rchenatjpl** [comment]
Hi, @alyssambailey, this has been ingested, though I rolled the version back to 1.0 since it's the first time it's been on the EN site.
https://pds.nasa.gov/ds-view/pds/viewContext.jsp?identifier=urn:nasa:pds:context:investigation%3Aother_investigation.clps
The file itself is near the bottom of https://pds.nasa.gov/data/pds4/context-pds4/investigation/

**Comment by jordanpadams** [comment]
@rchenatjpl are we good to lose this out?

**Comment by rchenatjpl** [comment]
yes, I probably should have closed it. Thanks
