### ISSUE TITLE
[ldd-release] Voyager LDD Version:1.0.0.0 IM Version:1.16, 1.17, 1.20, 1.21

### ISSUE THREAD

**Issue by matthewtiscareno** [NASA-PDS/operations#506]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date rationale

@rgdeen is ready to validate data products against this dictionary.

### GitHub Tagged Release of LDD

The corresponding URL would be https://github.com/pds-data-dictionaries/ldd-vgr/releases, but there are no releases there. 

I just now [merged v1.0.0.0](https://github.com/pds-data-dictionaries/ldd-vgr/pull/14), but I see only now from [these instructions](https://pds-data-dictionaries.github.io/development/ldd-release.html#preparing-a-release) that that merge should have had the word "release" in the branch name.  Of course, you cannot change the name of a branch once you've created it, so I was not able to meet that criterion.  I'm hoping EN can help me with whatever is still needed for this dictionary to be fully published and released.

### PDS4 IM Versions to Release

1.16, 1.17, 1.20, 1.21

**Comment by jordanpadams** [comment]
@matthewtiscareno I created a new `release/1.0.0` branch, and then [manually triggered the build of the LDD](https://github.com/pds-data-dictionaries/PDS-Data-Dictionaries.github.io/discussions/23), created a PR, merged, and the [release has been tagged](https://github.com/pds-data-dictionaries/ldd-vgr/releases/). 🎉

**Comment by matthewtiscareno** [comment]
Okay, I see how you did that.  I can do similarly in the future. 

Thanks, @jordanpadams!

**Comment by c-suh** [comment]
@matthewtiscareno these 4 LDDs have been posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#vgr!

**Comment by matthewtiscareno** [comment]
Great!  Thank you again, @c-suh and @jordanpadams 

@rgdeen:  Please proceed with using this LDD
