### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:nh_mvic::1.0 and urn:nasa:pds:nh_documents::1.0

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS/operations#507]
### Discipline Node Information

* **Delivering Node**: SBN-UMD

* **NSSDCA Delivery Packages**: 
  * https://pdssbn.astro.umd.edu/holdings/pds4-nh_documents-v1.0/SUPPORT/NSSDCA/
  * https://pdssbn.astro.umd.edu/holdings/pds4-nh_mvic-v1.0/SUPPORT/NSSDCA/

* **Validation reports**: 
  * https://pdssbn.astro.umd.edu/holdings/pds4-nh_documents-v1.0/SUPPORT/NSSDCA/nh_documents_v1.0_20240415_validate_rpt.txt
  * https://pdssbn.astro.umd.edu/holdings/pds4-nh_mvic-v1.0/SUPPORT/NSSDCA/nh_mvic_v1.0_20240415_validate_rpt.txt

Please note that PDF file validation error in the nh_documents bundle is expected.  There is a compliant copy of the PDF file also in the collection, but we felt we needed to preserve the original pdf that was grabbed from the National archives.

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by tbarnes4** [comment]
@c-suh Is there anything more you need from me to get this progressing for NSSDCA ingestion?  Thanks!

**Comment by c-suh** [comment]
@tbarnes4 my apologies for the delay. I've posted the NH MVIC package for NSSDCA, but please note that its [validation report](https://pdssbn.astro.umd.edu/holdings/pds4-nh_mvic-v1.0/SUPPORT/NSSDCA/nh_mvic_v1.0_20240415_validate_rpt.txt) for shows warnings about unallowed subdirectory names.  From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:nh_mvic_v1.0_20240415


For the NH Documents package, there is an error at the bottom of [the report](https://pdssbn.astro.umd.edu/holdings/pds4-nh_documents-v1.0/SUPPORT/NSSDCA/nh_documents_v1.0_20240415_validate_rpt.txt) which marks pluto_ao_original.pdf as not being PDF/A compliant. Please address this and let me know once done. Thank you!

**Comment by c-suh** [comment]
@tbarnes4 an update and another apology - I confused the procedure, and you do not need to address the PDF/A non-compliant file. I have also posted the NH Documents package, so starting tomorrow, you can check the status of both packages at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:nh_mvic_v1.0_20240415
* urn:nasa:pds:system_bundle:product_sip_deep_archive:nh_documents_v1.0_20240415

**Comment by tbarnes4** [comment]
@c-suh Thanks!

**Comment by tbarnes4** [comment]
Archived 2024-06-19.  Sorry for not closing sooner.
