### ISSUE TITLE
[ldd-release] Imaging LDD Version: 1890 IM Version: 1G00

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#508]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

within a week or two...? Need to check with Bob though. He still needs 1G00 of this Imaging version.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-img/releases/tag/1G00_1890

### PDS4 IM Versions to Release

1G00

**Comment by rgdeen** [comment]
I'm ready for this any time now... VGR-PDART bundle is ready for final validation but needs this first.

**Comment by c-suh** [comment]
@thareUSGS and @rgdeen this LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.16.0.0.shtml#img!
