### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:cassini-uvis_titan-library

### ISSUE THREAD

**Issue by tinagueth** [NASA-PDS/operations#513]
### Discipline Node Information

* **Delivering Node**: PDS_ATM

* **NSSDCA Delivery Package**: 
[cassini_uvis_titan_20240506.tar.gz](https://github.com/NASA-PDS/operations/files/15224373/cassini_uvis_titan_20240506.tar.gz)

* **Validation report**: 
[cassini_uvis_titan.txt](https://github.com/NASA-PDS/operations/files/15224376/cassini_uvis_titan.txt)

NOTE: If you have multiple delivery packages, we strongly encourage you to submit these in batches of 3 to 10 per issue with one ZIP file of the packages and another ZIP file of the validation reports. Please use a descriptive title, such as "Node Mission misc batch #".

----

### Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tinagueth this set has been posted for NSSDCA processing! From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:cassini-uvis_titan-library_v1.0_20240506

**Comment by tinagueth** [comment]
@c-suh Hi. Sorry for the delayed reply. Lyle informed me that that document was changed after I submitted it, and he said to resubmit it. I will be working on the resubmission of this and hope that is not a big problem. Sorry about this. Tina

**Comment by tinagueth** [comment]
resubmitted as #528

**Comment by jordanpadams** [comment]
Closing for #528
