### ISSUE TITLE
[ldd-release] img_surface LDD Version: 1280 IM Version: 1J00

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#514]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

soon, if possible

### Need by date rationale

needed for Mars 2020 release. The team needs the "1J00" IM version released. Only "1L00" was originally requested for release for this version.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-img_surface/releases/tag/1J00_1280

### PDS4 IM Versions to Release

1L00 already released. We need to add "1J00".

**Comment by c-suh** [comment]
@thareUSGS this LDD has been validated and posted at https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#img_surface!
