### ISSUE TITLE
[ldd-release] Voyager LDD Version:1.1.0 IM Version:1.16, 1.17, 1.20, 1.21

### ISSUE THREAD

**Issue by matthewtiscareno** [NASA-PDS/operations#515]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-vgr/releases/tag/1G00_1100
https://github.com/pds-data-dictionaries/ldd-vgr/releases/tag/1H00_1100
https://github.com/pds-data-dictionaries/ldd-vgr/releases/tag/1K00_1100
https://github.com/pds-data-dictionaries/ldd-vgr/releases/tag/1L00_1100

### PDS4 IM Versions to Release

1.16, 1.17, 1.20, 1.21

**Comment by c-suh** [comment]
@matthewtiscareno the LDDs for Voyager 1G00 (1.16.0.0), 1H00 (1.17.0.0), 1K00 (1.20.0.0), and 1L00 (1.21.0.0) 1100 have been posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#vgr!

**Comment by matthewtiscareno** [comment]
@c-suh:  Thanks!
