### ISSUE TITLE
[ldd-release] KPLO LDD Version: 1010 IM Version: 1L00

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#517]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

end week if possible

### Need by date rationale

For KPLO LUTI instrument team to start releasing data.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-kplo/releases/tag/1L00_1010

### PDS4 IM Versions to Release

1L00

**Comment by c-suh** [comment]
@thareUSGS the LDD for KPLO 1L00 1010 has been posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#kplo!
