### ISSUE TITLE
[ldd-release] Hubble Space Telescope (HST) LDD Version:1.0.1 IM Version:1H, 1L, 1M

### ISSUE THREAD

**Issue by matthewtiscareno** [NASA-PDS/operations#520]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-hst/releases

### PDS4 IM Versions to Release

1H00_101, 1L00_101, 1M00_101

**Comment by c-suh** [comment]
@matthewtiscareno these LDDs have been validated and posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#hst!

**Comment by matthewtiscareno** [comment]
Thanks, @c-suh!
