### ISSUE TITLE
[ldd-release] CTLI_1L00_2100

### ISSUE THREAD

**Issue by lylehuber** [NASA-PDS/operations#522]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

N/A

### Need by date rationale

N/A

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-ctli/releases/tag/1L00_2100

### PDS4 IM Versions to Release

1L00

**Comment by jordanpadams** [comment]
@lylehuber I removed `CTLI_1M00_2100` because that will be included in our nominal release process.

**Comment by jordanpadams** [comment]
I also linked to the repo release https://github.com/pds-data-dictionaries/ldd-ctli/releases/tag/1L00_2100

**Comment by c-suh** [comment]
@lylehuber this LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.21.0.0.shtml#ctli!
