### ISSUE TITLE
[ldd-release] CLPS LDD Version: 1.1.0.0 IM Version: 1.19.0.0-1.22.0.0

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#523]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

July 19, 2024

### Need by date rationale

This is the date of the first CLPS release (TO2_AB).

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-clps/releases

### PDS4 IM Versions to Release

1.19.0.0-1.22.0.0

**Comment by c-suh** [comment]
@jennifergward these LDDs have been validated and posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#clps!
