### ISSUE TITLE
[ldd-release] <New Horizons Mission Dictionary> LDD Version:<1.1.0.0> IM Version:<1.19.0.0>

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/operations#524]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

28 June 2024 or soon after

### Need by date rationale

Data are scheduled for release 28 June 2024. We would like the dictionary to be available as soon as possible on or after that date. This is a migration effort rather than a new mission data release, however, so the need is slightly less urgent than it might be otherwise.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-nh/releases/tag/1J00_1100

Note that the New Horizons mission has frozen on IM 1J00, so this is the only version we actually need.

### PDS4 IM Versions to Release

1J00_1100

**Comment by c-suh** [comment]
@acraugh this LDD has been validated and posted at https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#nh!
