### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:lcross_apo_agile::1.0 and urn:nasa:pds:lcross_mmt_ccd47::1.0 and urn:nasa:pds:lcross_mro_photdoc::1.0 and urn:nasa:pds:lcross_mro_photgjon::1.0 and urn:nasa:pds:lp_rs_jpl_gravity_derived::1.0 and urn:nasa:pds:xas_synthesized_glasses::1.0

### ISSUE THREAD

**Issue by alknight-wustl** [NASA-PDS/operations#525]
### Discipline Node Information

* **Delivering Node**: PDS Geosciences Node

* **NSSDCA Delivery Package**: 
[GEO_LCROSS_LP_Misc_delivery_packages_21_June_2024.zip](https://github.com/user-attachments/files/15932704/GEO_LCROSS_LP_Misc_delivery_packages_21_June_2024.zip)

* **Validation report**: 
[LCROSS_LP_Misc_validate_reports.zip](https://github.com/user-attachments/files/15932707/LCROSS_LP_Misc_validate_reports.zip)

**Comment by alknight-wustl** [comment]
The Geosciences Node is aware of the warning present in the validation reports for urn:nasa:pds:lcross_apo_agile::1.0 and urn:nasa:pds:lcross_mmt_ccd47::1.0 and urn:nasa:pds:lcross_mro_photdoc::1.0 and urn:nasa:pds:lcross_mro_photgjon::1.0. We are not planning on correcting it at this time.

**Comment by c-suh** [comment]
@alknight-wustl and @smclaughlin7, these 6 sets have been posted for NSSDCA processing! From tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LIDs below:

SIP LIDs:
urn:nasa:pds:system_bundle:product_sip_deep_archive:lcross_apo_agile_v1.0_20240614
urn:nasa:pds:system_bundle:product_sip_deep_archive:lcross_mmt_ccd47_v1.0_20240614
urn:nasa:pds:system_bundle:product_sip_deep_archive:lcross_mro_photdoc_v1.0_20240614
urn:nasa:pds:system_bundle:product_sip_deep_archive:lcross_mro_photgjon_v1.0_20240614
urn:nasa:pds:system_bundle:product_sip_deep_archive:lp_rs_jpl_gravity_derived_v1.0_20240614
urn:nasa:pds:system_bundle:product_sip_deep_archive:xas_synthesized_glasses_v1.0_20240614

**Comment by c-suh** [comment]
@alknight-wustl all 6 sets have been Ingested or Archived by NSSDCA.
