### ISSUE TITLE
[ldd-release] <Small Bodies Discipline Dictionary> LDD Version:<1.1.0.0> IM Version:<1J00 and 1M00>

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/operations#526]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

June 30 for the PDS4_SB_1J00_1100 schemas. Delay on the order of days is entirely acceptable.
When reasonably convenient for the PDS4_SB_1M00_1100 schemas.

### Need by date rationale

We are releasing data for the New Horizons migration effort June 30 and would like the PDS4_SB_1J00_1100 schemas available as soon as feasible on or after that date to support the data.  The migration and ongoing mission are frozen on IM 1.19.0.0.

Because the SB dictionary was in active development during the last build cycle, the 1M00 release was deferred until the development was complete. Consequently, we would also like to release the PDS4_SB_1M00_1100 schemas, but there is no urgent need for them that I know of - just want to make sure they are available if needed for new development.

### GitHub Tagged Release of LDD

[1J00_1100](https://github.com/pds-data-dictionaries/ldd-sb/releases/tag/1J00_1100)
[1M00_1100](https://github.com/pds-data-dictionaries/ldd-sb/releases/tag/1M00_1100)

### PDS4 IM Versions to Release

1M00 and 1J00

**Comment by jordanpadams** [comment]
@acraugh these have now been posted:

https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#sb
https://pds.nasa.gov/datastandards/dictionaries/index-1.22.0.0.shtml#sb
