### ISSUE TITLE
[ldd-request] Create new LDD "vikinglander"

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#527]
### Local Data Dictionary Name

Viking Lander

### LDD Short Name Identifier Requested

vikinglander

### Discipline or Mission Local Data Dictionary?

Mission

### LDD Steward Organization

PDS Geosciences Node

### LDD Steward Name

Jennifer Ward

### LDD Steward Email

jgward@wustl.edu

### LDD Steward Team Members

jennifergward, mnhughes, alknight-wustl

### LDD Description

The Viking Lander mission dictionary contains classes and attributes specific to the Viking Lander mission and its instruments.

### Rationale for creation of new LDD

To support Viking Lander migrations and new IDP submissions.

### ⚙️ Engineering Details

- [x] Complete [Initializing New LDD procedure](https://pds-data-dictionaries.github.io/development/ldd-create.html#initializing-new-ldd)
- [x] If Discipline LDD
  - [x] add Steward to pdsddstewards@jpl.nasa.gov email list if they are not already on the list
  - [ ] ~update [LDD script config](https://github.com/NASA-PDS/pdsen-operations/blob/master/conf/ldds/config.yml)~
  - [ ] ~create directory and index files for Git~
  - [ ] ~create symlink on all machines~
  - [ ] ~work with @jordanpadams to ping DD Stewards to establish CCB~

**Comment by jordanpadams** [comment]
@jennifergward @mnhughes @alknight-wustl your LDD repo is now ready for use at https://github.com/pds-data-dictionaries/ldd-vikinglander. Read through [Getting to Know Your LDD Repo](https://pds-data-dictionaries.github.io/getting-started.html#getting-to-know-your-ldd-repo) to get started.
