### ISSUE TITLE
Saturn Occultation of 28 Sagittarius 1989

### ISSUE THREAD

**Issue by matthewtiscareno** [NASA-PDS/operations#530]
* **PDS4 LID:** `urn:nasa:pds:context:investigation:mission.saturn_occultation_of_28_sagittarius_1989`

* **LID Type:** Context
  
* **Mission:** The worldwide effort to observe the occultation by Saturn of the star 28 Sgr, which took place on 3 July 1989

* **Responsible Node:** RMS

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Notes:**

A draft context product already exists [here](https://pds.nasa.gov/data/pds4/context-pds3/investigation/Product/mission_SATURN_OCCULTATION_OF_28_SAGITTARIUS_1989_1.0.xml), in the `context-pds3` folder which seems to date from 2016.  The LID there is `urn:nasa:pds:context_pds3:investigation:mission.saturn_occultation_of_28_sagittarius_1989`. 

This is one of three non-mission data sets that have long been part of the RMS holdings (the other two are in `context-pds3` as [this](https://pds.nasa.gov/data/pds4/context-pds3/investigation/Product/mission_SATURN_RING_PLANE_CROSSING_1995_1.0.xml) and [this](https://pds.nasa.gov/data/pds4/context-pds3/investigation/Product/mission_SATURN_SMALL_SATELLITE_ASTROMETRY_1.0.xml)).  The associated information page on the RMS website is [here](https://pds-rings.seti.org/ringocc/).  

For reasons unknown to us, 28 Sgr was left out when the other two (see [here](https://pds.nasa.gov/data/pds4/context-pds4/investigation/mission.saturn_ring_plane_crossing_1995_1.1.xml) and [here](https://pds.nasa.gov/data/pds4/context-pds4/investigation/mission.saturn_small_satellite_astrometry_1.1.xml)) were migrated to the `context-pds4` folder, apparently in 2021.  That was the occasion on which the other two data sets received proper LIDs, so 28 Sgr should receive one that follows the same form.

**Comment by rchenatjpl** [comment]
Hi, Matt, the LIDs that include context_pds3 are stopgaps from the transition to PDS4. Can you dump the two "this"s in your message from your holdings, i.e.
```
urn:nasa:pds:context_pds3:investigation:mission.saturn_ring_plane_crossing_1995
urn:nasa:pds:context_pds3:investigation:mission.saturn_small_satellite_astrometry
```
We can modify the two fully PDS4 equivalents to add 28 sgr, as well as add that to the "new" mission. Let me modify those three to remove "_pds3", add lid_reference to 28 sgr, change all lidvid_reference to lid_reference, as well as create a context product for 28 sgr.

If desired, I can take care of a couple of commented out lid_references in the saturn_ring_place_crossing_1995, the target s_ring and the facility+telescope 4.2m William Herschel Telescope.

**Comment by matthewtiscareno** [comment]
Hi @rchenatjpl.  What do you mean by "dump the two 'this's"?  What exactly is the action you are suggesting? 

Also, what do you mean by "remove '_pds3'" and so forth?  The products in the `context-pds4` folder already do not contain the string "_pds3". 

Updating the products in the `context-pds4` folder is part of the EdWG's work, and RMS will be taking responsibility for the three investigations mentioned in this thread.  I'm sure we'd be glad of your help as that task takes shape, but conversations are still in early stages.

**Comment by rchenatjpl** [comment]
Hi, Matt, from your holdings, drop the context products that begin "urn:nasa:pds:context_pds3:". If you have any label that has a lid_reference to such a LID, replace it with the equivalent "urn:nasa:pds:context:". If such a product doesn't exist yet, we'll create it.

**Comment by matthewtiscareno** [comment]
@rchenatjpl:  We do not have any `context_pds3` context products in our holdings.  Other than the "associated information page," all of the links in my original statement are to items maintained by EN. 

I filed this issue at the instruction of @jordanpadams.  I believe the purpose is simply to set aside the LID.  We will be updating all of the context products as part of the EdWG's work.

**Comment by rchenatjpl** [comment]
@matthewtiscareno , in your original message here, what's linked to "this" and "this"?

**Comment by matthewtiscareno** [comment]
> @matthewtiscareno , in your original message here, what's linked to "this" and "this"?

You can see the URLs yourself, right? This is EN context product repository, in the `context-pds3` directory.

**Comment by rchenatjpl** [comment]
@matthewtiscareno Sorry, I didn't notice the URLs. I thought you said those two context products were part of your holdings. So all you want is to reserve the LID? That's fine. If you want help with the context product, please say so. Attached is what the 28 Sgr context product should be.
[star.26_tau_1.0.xml.zip](https://github.com/user-attachments/files/16371872/star.26_tau_1.0.xml.zip)

**Comment by matthewtiscareno** [comment]
@rchenatjpl:  Yes, all we want for this issue is to reserve the LID. 

Good catch that we will want a context product for the target star, as well as one for the investigation.  Your attached file has a filename indicating that it applies to 28 Tau, but the content does indeed seem to apply to 28 Sgr.  

Did you generate all of the correct aliases for this particular star?  Thanks for doing that.  Can we go ahead and put this into the archive, so that it will be there when we want it?

**Comment by jordanpadams** [comment]
thanks @matthewtiscareno @rchenatjpl . We will be sure to work this offline and reserve the new LID.

**Comment by rchenatjpl** [comment]
The mission LID is reserved, but upon greater reflection, can we replace "mission." with "observing_campaign.", i.e. change
urn:nasa:pds:context:investigation:mission.saturn_occultation_of_28_sagittarius_1989
to
urn:nasa:pds:context:investigation:observing_campaign.saturn_occultation_of_28_sagittarius_1989
We already have a few other such investigations. Is that all right?

**Comment by rchenatjpl** [comment]
@matthewtiscareno The mission LID is reserved, but upon greater reflection, can we replace "mission." with "observing_campaign.", i.e. change
urn:nasa:pds:context:investigation:mission.saturn_occultation_of_28_sagittarius_1989
to
urn:nasa:pds:context:investigation:observing_campaign.saturn_occultation_of_28_sagittarius_1989
We already have a few other such investigations. Is that all right?

**Comment by matthewtiscareno** [comment]
> @matthewtiscareno The mission LID is reserved, but upon greater reflection, can we replace "mission." with "observing_campaign."

This is fine with me, but can we do the same for `saturn_ring_plane_crossing_1995` and `saturn_small_satellite_astrometry`?  It would make sense for all three LIDs to be formed consistently.

**Comment by rchenatjpl** [comment]
wow, right. Thanks, @matthewtiscareno . Let me ask SBN if anyone there is using them.

**Comment by matthewtiscareno** [comment]
It's doubtful that anyone is using them, but it's good to check.  These are old RMS data sets.  If anyone is going to migrate them to PDS4, it will be us.

**Comment by rchenatjpl** [comment]
Matt, I shouldn't have checked. No one else is using those two, and I probably could have replaced them without anyone knowing, but I hit a wall trying to deprecate old LIDs, ie. the suboptimal ones are set in stone. Sorry about that.

**Comment by jordanpadams** [comment]
@rchenatjpl has this context LID been created?

**Comment by rchenatjpl** [comment]
@jordanpadams No, it's only been approved, and the LID is visible at https://pds-engineering.jpl.nasa.gov/discipline-node-help/context-lids/. I could create the context product based on Matt's draft context product at the top of this issue, but I would replace the references to any context_pds3 LIDs, which might mean creating other context products

**Comment by jordanpadams** [comment]
@rchenatjpl no worries. the LID is enough for me.
