### ISSUE TITLE
[ldd-release] ODY LDD Version: 1.0.0.0 IM Version: 1.19.0.0-1.21.0.0

### ISSUE THREAD

**Issue by dvpolitte** [NASA-PDS/operations#531]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

1 September 2024

### Need by date rationale

Migrated ODY data will be released on 1 October 2024 that use this LDD; the requested date includes some lead-time for final preparations of the migrated datasets.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-ody/releases

### PDS4 IM Versions to Release

1.19.0.0, 1.20.0.0, 1.21.0.0

**Comment by thareUSGS** [comment]
Imaging could use this sooner for an upcoming THEMIS review. Ideally next week if possible

**Comment by jordanpadams** [comment]
@dvpolitte this is done. https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#ody
