### ISSUE TITLE
[ldd-release] Viking Lander LDD Version: 1.0.0.0 IM Version: 1.21.0.0-1.22.0.0 

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#534]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

9/1/24

### Need by date rationale

To support migration of VL datasets.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-vikinglander/releases

### PDS4 IM Versions to Release

1.21.0.0-1.22.0.0

**Comment by jordanpadams** [comment]
@jennifergward this is done: https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#vikinglander
