### ISSUE TITLE
[lid-request] urn:nasa:pds:context:investigation:mission.slim, urn:nasa:pds:context:instrument_host:spacecraft.slim, urn:nasa:pds:context:instrument:slim.lra

### ISSUE THREAD

**Issue by jennifergward** [NASA-PDS/operations#535]
* **PDS4 LID:** 
urn:nasa:pds:context:investigation:mission.slim
urn:nasa:pds:context:instrument_host:spacecraft.slim
urn:nasa:pds:context:instrument:slim.lra

* **LID Type:**
Context
  
* **Mission:**
SLIM (Smart Lander for Investigating Moon)

* **Responsible Node:**
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
@jennifergward , these sound fine. Do you have the context products already? Or soon? I'm about to copy stuff in, and it'd be great to push them all at once. Thanks

**Comment by jennifergward** [comment]
I haven't started on them yet. Sorry.

**Comment by rchenatjpl** [comment]
Great. Thanks, they're there now.
