### ISSUE TITLE
[ldd-release] IMG LDD Version: 1.8.9.0 IM Version: 1.19.0.0 (1J00)

### ISSUE THREAD

**Issue by acraugh** [NASA-PDS/operations#537]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

As soon as convenient. 

### Need by date rationale

The New Horizons mission is frozen on IM 1J00, but needs some of the later developments in the IMG 1890 dictionary both for incoming data from the extended mission, as well as by SBN for the migration of legacy PDS3 data. The PDS4_IMG_1J00_1890 schema files are available in the ldd-img build directory, but are not in the https://pds.nasa.gov/pds4/img/v1/ directory.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-img/releases/tag/1J00_1890

### PDS4 IM Versions to Release

1J00

**Comment by jordanpadams** [comment]
This LDD release has been completed
