### ISSUE TITLE
Release calendar updates for New Horizons

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#542]
## 💡 Description

- Correct the Lucy Dinkinesh Anticipated Release Date from "10/TBD/2024" to be "10/14/2024".  This should affect 6 entries, L'LORRI, L'Ralph LEISA, L'Ralph MVIC, L'TES, Radio Science, and TTCam
- Add an entry for New Horizons/KEM2, LORRI, K7: New Arrokoth Shape Model, Irregular, 10/07/2024 [as the anticipated release date]
- Remove the four "New Horizons/KEM1" and six of seven "New Horizons" entries.  They are a migration effort of PDS3 to PDS4, and the original PDS3 versions being released April 2023.  So they have been available for proposers for over a year.
  - New Horizons Alice KEM1 Encounter Calibrated Data
  - New Horizons Alice KEM1 Encounter Raw Data
  - New Horizons LORRI KEM1 Encounter Calibrated Data
  - New Horizons LORRI KEM1 Encounter Raw Data
  - New Horizons Alice Reference Files Used in Calibrating Data
  - New Horizons Documents for the Alice Instrument
  - New Horizons Documents for the LORRI Instrument
  - New Horizons LORRI Reference Files Used in Calibrating Data
  - New Horizons Mission Documents v2.0

**Comment by c-suh** [comment]
Changes made and operational. Will be sending email shortly.
