### ISSUE TITLE
[ldd-release] Particle LDD Version:2020 IM Version:1.22.0.0 (1M00)

### ISSUE THREAD

**Issue by jmafi** [NASA-PDS/operations#556]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

11 Oct 2024

### Need by date rationale

This update includes a new permissible value which is needed for a PDS4 migration that is currently in progress. This migration is in the final lien resolution stage and needs this update in order to be completed.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-particle/tree/main/build/development/296f2914c35335b428c3e6d61cb84d81b5d68564

### PDS4 IM Versions to Release

1.22.0.0

**Comment by jordanpadams** [comment]
@jmafi Sorry for the delay hear. To clarify, you are looking to release LDD version 2.0.1.0? https://github.com/pds-data-dictionaries/ldd-particle/releases

**Comment by jordanpadams** [comment]
@jmafi got it. In the future, this is considered an "Off Nominal Release" of the LDD (aka not on our normal 6-month cadence for releases), which has some additional requirements on the LDD Steward to tag a new release. https://pds-data-dictionaries.github.io/development/ldd-release.html#off-nominal-release

I will take care of this for this go around.

**Comment by jordanpadams** [comment]
@jmafi this is done and should go live in <1 hour
