### ISSUE TITLE
magellan_bsr_calibrated

### ISSUE THREAD

**Issue by eischaefer** [NASA-PDS/operations#561]
* **PDS4 LID:** magellan_bsr_calibrated

* **LID Type:** Bundle
  
* **Mission:** Magellan

* **Responsible Node:** Geosciences

**NOTE:** This bundle name will replace `magellan_bsr_derived`, which was reserved earlier (on or sometime shortly after May 21, 2024, by Ed Guinness) but never used (and will not be used).

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
_derived is removed, and _calibrated is added. Thanks for notifying us of the deletion, Ethan
