### ISSUE TITLE
[ldd-release] ODY; Version: 1010; IM Version: L, K, J

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/operations#564]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

early Nov. would be great.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-ody/releases

### PDS4 IM Versions to Release

1L00_1010
1K00_1010
1J00_1010

**Comment by jordanpadams** [comment]
@thareUSGS this is done and should go live in 1 hour or less
