### ISSUE TITLE
[lid-request] urn:nasa:pds:msl_apxs_native_sulfur_supplement

### ISSUE THREAD

**Issue by alknight-wustl** [NASA-PDS/operations#566]
* **PDS4 LID:** 
urn:nasa:pds:msl_apxs_native_sulfur_supplement

* **LID Type:** 
Bundle
  
* **Mission:** 
Mars Science Laboratory (individual investigator)

* **Responsible Node:** 
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
done a while ago. Sorry I forgot to close this
