### ISSUE TITLE
[lid-request] urn:nasa:pds:phx_tega_egh_pm

### ISSUE THREAD

**Issue by alknight-wustl** [NASA-PDS/operations#567]
* **PDS4 LID:** 
urn:nasa:pds:phx_tega_egh_pm

* **LID Type:** 
Bundle
  
* **Mission:** 
Phoenix (individual investigator)

* **Responsible Node:**
GEO

---

See all PDS4 Bundle LIDs at https://pds-engineering.jpl.nasa.gov/content/bundle-lids.

**Comment by rchenatjpl** [comment]
d@mnit, forgot to close this a while ago. It's done
