### ISSUE TITLE
[ldd-release] GEOM LDD Version:1980 IM Version:1J00

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/operations#570]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

ASAP

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-geom/releases/tag/1J00_1980

**Comment by c-suh** [comment]
@jordanpadams would you like me to handle this? I can do so today

**Comment by c-suh** [comment]
This LDD has been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-1.19.0.0.shtml#geom! Please allow up to 15 minutes from now for the changes to appear.

**Comment by alknight-wustl** [comment]
@jordanpadams @c-suh Thank you so much!!
