### ISSUE TITLE
Lucy Mission Dictionary Initial Release

### ISSUE THREAD

**Issue by katecrombie** [NASA-PDS/operations#571]
### Is the LDD IngestLDD in Github?

Yes

### Has the LDD Namespace been registered in the Namespace Registry?

Yes

### Need by date?

January 15, 2025

### Need by date rationale

Liens resolved data products will be made public on this date.

### GitHub Tagged Release of LDD

https://github.com/pds-data-dictionaries/ldd-lucy/releases

### PDS4 IM Versions to Release

IM 1.20 
IM 1.18

**Comment by c-suh** [comment]
Hi @katecrombie - these two LDDs have been validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index-missions.shtml#lucy.

Happy New Year!
